# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui\mainwindow.ui'
#
# Created: Thu Feb 05 21:23:13 2015
#      by: PyQt4 UI code generator 4.9.6
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(1168, 853)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/turbinedaq.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtGui.QWidget(MainWindow)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.gridLayout_4 = QtGui.QGridLayout(self.centralwidget)
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.dockWidgetNISignals = QtGui.QDockWidget(self.centralwidget)
        self.dockWidgetNISignals.setFloating(False)
        self.dockWidgetNISignals.setFeatures(QtGui.QDockWidget.AllDockWidgetFeatures)
        self.dockWidgetNISignals.setAllowedAreas(QtCore.Qt.AllDockWidgetAreas)
        self.dockWidgetNISignals.setObjectName(_fromUtf8("dockWidgetNISignals"))
        self.dockWidgetContents_2 = QtGui.QWidget()
        self.dockWidgetContents_2.setObjectName(_fromUtf8("dockWidgetContents_2"))
        self.gridLayout_8 = QtGui.QGridLayout(self.dockWidgetContents_2)
        self.gridLayout_8.setObjectName(_fromUtf8("gridLayout_8"))
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.label = QtGui.QLabel(self.dockWidgetContents_2)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName(_fromUtf8("label"))
        self.verticalLayout_2.addWidget(self.label)
        self.plotTorque = CurveWidget(self.dockWidgetContents_2)
        self.plotTorque.setOrientation(QtCore.Qt.Horizontal)
        self.plotTorque.setObjectName(_fromUtf8("plotTorque"))
        self.verticalLayout_2.addWidget(self.plotTorque)
        self.label_2 = QtGui.QLabel(self.dockWidgetContents_2)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.verticalLayout_2.addWidget(self.label_2)
        self.plotDrag = CurveWidget(self.dockWidgetContents_2)
        self.plotDrag.setOrientation(QtCore.Qt.Horizontal)
        self.plotDrag.setObjectName(_fromUtf8("plotDrag"))
        self.verticalLayout_2.addWidget(self.plotDrag)
        self.label_12 = QtGui.QLabel(self.dockWidgetContents_2)
        self.label_12.setAlignment(QtCore.Qt.AlignCenter)
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.verticalLayout_2.addWidget(self.label_12)
        self.plotDragL = CurveWidget(self.dockWidgetContents_2)
        self.plotDragL.setOrientation(QtCore.Qt.Horizontal)
        self.plotDragL.setObjectName(_fromUtf8("plotDragL"))
        self.verticalLayout_2.addWidget(self.plotDragL)
        self.label_13 = QtGui.QLabel(self.dockWidgetContents_2)
        self.label_13.setAlignment(QtCore.Qt.AlignCenter)
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.verticalLayout_2.addWidget(self.label_13)
        self.plotDragR = CurveWidget(self.dockWidgetContents_2)
        self.plotDragR.setOrientation(QtCore.Qt.Horizontal)
        self.plotDragR.setObjectName(_fromUtf8("plotDragR"))
        self.verticalLayout_2.addWidget(self.plotDragR)
        self.label_16 = QtGui.QLabel(self.dockWidgetContents_2)
        self.label_16.setAlignment(QtCore.Qt.AlignCenter)
        self.label_16.setObjectName(_fromUtf8("label_16"))
        self.verticalLayout_2.addWidget(self.label_16)
        self.plotRPM_ni = CurveWidget(self.dockWidgetContents_2)
        self.plotRPM_ni.setOrientation(QtCore.Qt.Horizontal)
        self.plotRPM_ni.setObjectName(_fromUtf8("plotRPM_ni"))
        self.verticalLayout_2.addWidget(self.plotRPM_ni)
        self.gridLayout_8.addLayout(self.verticalLayout_2, 0, 0, 1, 1)
        self.dockWidgetNISignals.setWidget(self.dockWidgetContents_2)
        self.gridLayout_4.addWidget(self.dockWidgetNISignals, 0, 1, 2, 1)
        self.dockWidgetVectrino = QtGui.QDockWidget(self.centralwidget)
        self.dockWidgetVectrino.setMinimumSize(QtCore.QSize(198, 601))
        self.dockWidgetVectrino.setFeatures(QtGui.QDockWidget.AllDockWidgetFeatures)
        self.dockWidgetVectrino.setObjectName(_fromUtf8("dockWidgetVectrino"))
        self.dockWidgetContents = QtGui.QWidget()
        self.dockWidgetContents.setObjectName(_fromUtf8("dockWidgetContents"))
        self.gridLayout_6 = QtGui.QGridLayout(self.dockWidgetContents)
        self.gridLayout_6.setObjectName(_fromUtf8("gridLayout_6"))
        self.verticalLayout_3 = QtGui.QVBoxLayout()
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.label_vecu = QtGui.QLabel(self.dockWidgetContents)
        self.label_vecu.setAlignment(QtCore.Qt.AlignCenter)
        self.label_vecu.setObjectName(_fromUtf8("label_vecu"))
        self.verticalLayout_3.addWidget(self.label_vecu)
        self.plotVecU = CurveWidget(self.dockWidgetContents)
        self.plotVecU.setOrientation(QtCore.Qt.Horizontal)
        self.plotVecU.setObjectName(_fromUtf8("plotVecU"))
        self.verticalLayout_3.addWidget(self.plotVecU)
        self.label_11 = QtGui.QLabel(self.dockWidgetContents)
        self.label_11.setAlignment(QtCore.Qt.AlignCenter)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.verticalLayout_3.addWidget(self.label_11)
        self.plotVecV = CurveWidget(self.dockWidgetContents)
        self.plotVecV.setOrientation(QtCore.Qt.Horizontal)
        self.plotVecV.setObjectName(_fromUtf8("plotVecV"))
        self.verticalLayout_3.addWidget(self.plotVecV)
        self.label_14 = QtGui.QLabel(self.dockWidgetContents)
        self.label_14.setAlignment(QtCore.Qt.AlignCenter)
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.verticalLayout_3.addWidget(self.label_14)
        self.plotVecW = CurveWidget(self.dockWidgetContents)
        self.plotVecW.setOrientation(QtCore.Qt.Horizontal)
        self.plotVecW.setObjectName(_fromUtf8("plotVecW"))
        self.verticalLayout_3.addWidget(self.plotVecW)
        self.label_15 = QtGui.QLabel(self.dockWidgetContents)
        self.label_15.setAlignment(QtCore.Qt.AlignCenter)
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.verticalLayout_3.addWidget(self.label_15)
        self.plotVecCorr = CurveWidget(self.dockWidgetContents)
        self.plotVecCorr.setOrientation(QtCore.Qt.Horizontal)
        self.plotVecCorr.setObjectName(_fromUtf8("plotVecCorr"))
        self.verticalLayout_3.addWidget(self.plotVecCorr)
        self.label_5 = QtGui.QLabel(self.dockWidgetContents)
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.verticalLayout_3.addWidget(self.label_5)
        self.plotVecSNR = CurveWidget(self.dockWidgetContents)
        self.plotVecSNR.setOrientation(QtCore.Qt.Horizontal)
        self.plotVecSNR.setObjectName(_fromUtf8("plotVecSNR"))
        self.verticalLayout_3.addWidget(self.plotVecSNR)
        self.gridLayout_6.addLayout(self.verticalLayout_3, 0, 0, 1, 1)
        self.dockWidgetVectrino.setWidget(self.dockWidgetContents)
        self.gridLayout_4.addWidget(self.dockWidgetVectrino, 0, 2, 2, 1)
        self.dockWidget_FBG = QtGui.QDockWidget(self.centralwidget)
        self.dockWidget_FBG.setMinimumSize(QtCore.QSize(198, 601))
        self.dockWidget_FBG.setFeatures(QtGui.QDockWidget.AllDockWidgetFeatures)
        self.dockWidget_FBG.setObjectName(_fromUtf8("dockWidget_FBG"))
        self.dockWidgetContents_4 = QtGui.QWidget()
        self.dockWidgetContents_4.setObjectName(_fromUtf8("dockWidgetContents_4"))
        self.gridLayout_7 = QtGui.QGridLayout(self.dockWidgetContents_4)
        self.gridLayout_7.setObjectName(_fromUtf8("gridLayout_7"))
        self.verticalLayout_4 = QtGui.QVBoxLayout()
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.label_FBG_1 = QtGui.QLabel(self.dockWidgetContents_4)
        self.label_FBG_1.setAlignment(QtCore.Qt.AlignCenter)
        self.label_FBG_1.setObjectName(_fromUtf8("label_FBG_1"))
        self.verticalLayout_4.addWidget(self.label_FBG_1)
        self.plot_FBG_1 = CurveWidget(self.dockWidgetContents_4)
        self.plot_FBG_1.setOrientation(QtCore.Qt.Horizontal)
        self.plot_FBG_1.setObjectName(_fromUtf8("plot_FBG_1"))
        self.verticalLayout_4.addWidget(self.plot_FBG_1)
        self.label_FBG_2 = QtGui.QLabel(self.dockWidgetContents_4)
        self.label_FBG_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_FBG_2.setObjectName(_fromUtf8("label_FBG_2"))
        self.verticalLayout_4.addWidget(self.label_FBG_2)
        self.plot_FBG_2 = CurveWidget(self.dockWidgetContents_4)
        self.plot_FBG_2.setOrientation(QtCore.Qt.Horizontal)
        self.plot_FBG_2.setObjectName(_fromUtf8("plot_FBG_2"))
        self.verticalLayout_4.addWidget(self.plot_FBG_2)
        self.label_FBG_3 = QtGui.QLabel(self.dockWidgetContents_4)
        self.label_FBG_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_FBG_3.setObjectName(_fromUtf8("label_FBG_3"))
        self.verticalLayout_4.addWidget(self.label_FBG_3)
        self.plot_FBG_3 = CurveWidget(self.dockWidgetContents_4)
        self.plot_FBG_3.setOrientation(QtCore.Qt.Horizontal)
        self.plot_FBG_3.setObjectName(_fromUtf8("plot_FBG_3"))
        self.verticalLayout_4.addWidget(self.plot_FBG_3)
        self.label_FBG_4 = QtGui.QLabel(self.dockWidgetContents_4)
        self.label_FBG_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_FBG_4.setObjectName(_fromUtf8("label_FBG_4"))
        self.verticalLayout_4.addWidget(self.label_FBG_4)
        self.plot_FBG_4 = CurveWidget(self.dockWidgetContents_4)
        self.plot_FBG_4.setOrientation(QtCore.Qt.Horizontal)
        self.plot_FBG_4.setObjectName(_fromUtf8("plot_FBG_4"))
        self.verticalLayout_4.addWidget(self.plot_FBG_4)
        self.label_FBG_5 = QtGui.QLabel(self.dockWidgetContents_4)
        self.label_FBG_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_FBG_5.setObjectName(_fromUtf8("label_FBG_5"))
        self.verticalLayout_4.addWidget(self.label_FBG_5)
        self.plot_FBG_5 = CurveWidget(self.dockWidgetContents_4)
        self.plot_FBG_5.setOrientation(QtCore.Qt.Horizontal)
        self.plot_FBG_5.setObjectName(_fromUtf8("plot_FBG_5"))
        self.verticalLayout_4.addWidget(self.plot_FBG_5)
        self.gridLayout_7.addLayout(self.verticalLayout_4, 0, 0, 1, 1)
        self.dockWidget_FBG.setWidget(self.dockWidgetContents_4)
        self.gridLayout_4.addWidget(self.dockWidget_FBG, 0, 3, 2, 1)
        self.dockWidget_acscontrol = QtGui.QDockWidget(self.centralwidget)
        self.dockWidget_acscontrol.setMinimumSize(QtCore.QSize(198, 380))
        self.dockWidget_acscontrol.setMaximumSize(QtCore.QSize(389, 524287))
        self.dockWidget_acscontrol.setFloating(False)
        self.dockWidget_acscontrol.setFeatures(QtGui.QDockWidget.DockWidgetMovable)
        self.dockWidget_acscontrol.setObjectName(_fromUtf8("dockWidget_acscontrol"))
        self.dockWidgetContents_3 = QtGui.QWidget()
        self.dockWidgetContents_3.setObjectName(_fromUtf8("dockWidgetContents_3"))
        self.verticalLayout_5 = QtGui.QVBoxLayout(self.dockWidgetContents_3)
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.tableWidget_acs = QtGui.QTableWidget(self.dockWidgetContents_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tableWidget_acs.sizePolicy().hasHeightForWidth())
        self.tableWidget_acs.setSizePolicy(sizePolicy)
        self.tableWidget_acs.setMinimumSize(QtCore.QSize(0, 112))
        self.tableWidget_acs.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.tableWidget_acs.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.tableWidget_acs.setEditTriggers(QtGui.QAbstractItemView.NoEditTriggers)
        self.tableWidget_acs.setProperty("showDropIndicator", True)
        self.tableWidget_acs.setDragDropOverwriteMode(False)
        self.tableWidget_acs.setSelectionMode(QtGui.QAbstractItemView.NoSelection)
        self.tableWidget_acs.setShowGrid(True)
        self.tableWidget_acs.setObjectName(_fromUtf8("tableWidget_acs"))
        self.tableWidget_acs.setColumnCount(6)
        self.tableWidget_acs.setRowCount(4)
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter|QtCore.Qt.AlignCenter)
        self.tableWidget_acs.setVerticalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_acs.setVerticalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_acs.setVerticalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_acs.setVerticalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter|QtCore.Qt.AlignCenter)
        self.tableWidget_acs.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_acs.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_acs.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_acs.setHorizontalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_acs.setHorizontalHeaderItem(4, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_acs.setHorizontalHeaderItem(5, item)
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter|QtCore.Qt.AlignCenter)
        self.tableWidget_acs.setItem(0, 0, item)
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter|QtCore.Qt.AlignCenter)
        self.tableWidget_acs.setItem(0, 1, item)
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter|QtCore.Qt.AlignCenter)
        self.tableWidget_acs.setItem(0, 2, item)
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter|QtCore.Qt.AlignCenter)
        self.tableWidget_acs.setItem(0, 3, item)
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter|QtCore.Qt.AlignCenter)
        self.tableWidget_acs.setItem(0, 4, item)
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter|QtCore.Qt.AlignCenter)
        self.tableWidget_acs.setItem(0, 5, item)
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter|QtCore.Qt.AlignCenter)
        self.tableWidget_acs.setItem(1, 0, item)
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter|QtCore.Qt.AlignCenter)
        self.tableWidget_acs.setItem(1, 1, item)
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter|QtCore.Qt.AlignCenter)
        self.tableWidget_acs.setItem(1, 2, item)
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter|QtCore.Qt.AlignCenter)
        self.tableWidget_acs.setItem(1, 3, item)
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter|QtCore.Qt.AlignCenter)
        self.tableWidget_acs.setItem(1, 4, item)
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter|QtCore.Qt.AlignCenter)
        self.tableWidget_acs.setItem(1, 5, item)
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter|QtCore.Qt.AlignCenter)
        self.tableWidget_acs.setItem(2, 0, item)
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter|QtCore.Qt.AlignCenter)
        self.tableWidget_acs.setItem(2, 1, item)
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter|QtCore.Qt.AlignCenter)
        self.tableWidget_acs.setItem(2, 2, item)
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter|QtCore.Qt.AlignCenter)
        self.tableWidget_acs.setItem(2, 3, item)
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter|QtCore.Qt.AlignCenter)
        self.tableWidget_acs.setItem(2, 4, item)
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter|QtCore.Qt.AlignCenter)
        self.tableWidget_acs.setItem(2, 5, item)
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter|QtCore.Qt.AlignCenter)
        self.tableWidget_acs.setItem(3, 0, item)
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter|QtCore.Qt.AlignCenter)
        self.tableWidget_acs.setItem(3, 1, item)
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter|QtCore.Qt.AlignCenter)
        self.tableWidget_acs.setItem(3, 2, item)
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter|QtCore.Qt.AlignCenter)
        self.tableWidget_acs.setItem(3, 3, item)
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter|QtCore.Qt.AlignCenter)
        self.tableWidget_acs.setItem(3, 4, item)
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter|QtCore.Qt.AlignCenter)
        self.tableWidget_acs.setItem(3, 5, item)
        self.tableWidget_acs.horizontalHeader().setCascadingSectionResizes(False)
        self.tableWidget_acs.horizontalHeader().setDefaultSectionSize(61)
        self.tableWidget_acs.horizontalHeader().setMinimumSectionSize(23)
        self.tableWidget_acs.horizontalHeader().setStretchLastSection(True)
        self.tableWidget_acs.verticalHeader().setVisible(False)
        self.tableWidget_acs.verticalHeader().setCascadingSectionResizes(False)
        self.tableWidget_acs.verticalHeader().setDefaultSectionSize(22)
        self.tableWidget_acs.verticalHeader().setHighlightSections(False)
        self.tableWidget_acs.verticalHeader().setMinimumSectionSize(15)
        self.tableWidget_acs.verticalHeader().setSortIndicatorShown(False)
        self.tableWidget_acs.verticalHeader().setStretchLastSection(False)
        self.verticalLayout_5.addWidget(self.tableWidget_acs)
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.label_26 = QtGui.QLabel(self.dockWidgetContents_3)
        self.label_26.setAlignment(QtCore.Qt.AlignCenter)
        self.label_26.setObjectName(_fromUtf8("label_26"))
        self.verticalLayout.addWidget(self.label_26)
        self.plotTowSpeed = CurveWidget(self.dockWidgetContents_3)
        self.plotTowSpeed.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.plotTowSpeed.setOrientation(QtCore.Qt.Horizontal)
        self.plotTowSpeed.setObjectName(_fromUtf8("plotTowSpeed"))
        self.verticalLayout.addWidget(self.plotTowSpeed)
        self.label_27 = QtGui.QLabel(self.dockWidgetContents_3)
        self.label_27.setAlignment(QtCore.Qt.AlignCenter)
        self.label_27.setObjectName(_fromUtf8("label_27"))
        self.verticalLayout.addWidget(self.label_27)
        self.plotRPM_acs = CurveWidget(self.dockWidgetContents_3)
        self.plotRPM_acs.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.plotRPM_acs.setOrientation(QtCore.Qt.Horizontal)
        self.plotRPM_acs.setObjectName(_fromUtf8("plotRPM_acs"))
        self.verticalLayout.addWidget(self.plotRPM_acs)
        self.verticalLayout_5.addLayout(self.verticalLayout)
        self.dockWidget_acscontrol.setWidget(self.dockWidgetContents_3)
        self.gridLayout_4.addWidget(self.dockWidget_acscontrol, 1, 0, 1, 1)
        self.tabWidgetMode = QtGui.QTabWidget(self.centralwidget)
        self.tabWidgetMode.setMinimumSize(QtCore.QSize(385, 300))
        self.tabWidgetMode.setMaximumSize(QtCore.QSize(389, 374))
        self.tabWidgetMode.setObjectName(_fromUtf8("tabWidgetMode"))
        self.tabSingleRun = QtGui.QWidget()
        self.tabSingleRun.setObjectName(_fromUtf8("tabSingleRun"))
        self.gridLayoutWidget_4 = QtGui.QWidget(self.tabSingleRun)
        self.gridLayoutWidget_4.setGeometry(QtCore.QRect(10, 10, 211, 251))
        self.gridLayoutWidget_4.setObjectName(_fromUtf8("gridLayoutWidget_4"))
        self.gridLayout_singleRun = QtGui.QGridLayout(self.gridLayoutWidget_4)
        self.gridLayout_singleRun.setMargin(0)
        self.gridLayout_singleRun.setObjectName(_fromUtf8("gridLayout_singleRun"))
        self.label_34 = QtGui.QLabel(self.gridLayoutWidget_4)
        self.label_34.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_34.setObjectName(_fromUtf8("label_34"))
        self.gridLayout_singleRun.addWidget(self.label_34, 1, 0, 1, 1)
        self.doubleSpinBox_singleRun_y_R = QtGui.QDoubleSpinBox(self.gridLayoutWidget_4)
        self.doubleSpinBox_singleRun_y_R.setMinimum(-3.0)
        self.doubleSpinBox_singleRun_y_R.setMaximum(3.0)
        self.doubleSpinBox_singleRun_y_R.setSingleStep(0.1)
        self.doubleSpinBox_singleRun_y_R.setObjectName(_fromUtf8("doubleSpinBox_singleRun_y_R"))
        self.gridLayout_singleRun.addWidget(self.doubleSpinBox_singleRun_y_R, 4, 1, 1, 1)
        self.label_3 = QtGui.QLabel(self.gridLayoutWidget_4)
        self.label_3.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout_singleRun.addWidget(self.label_3, 0, 0, 1, 1)
        self.doubleSpinBox_singleRun_U = QtGui.QDoubleSpinBox(self.gridLayoutWidget_4)
        self.doubleSpinBox_singleRun_U.setMaximum(2.0)
        self.doubleSpinBox_singleRun_U.setSingleStep(0.1)
        self.doubleSpinBox_singleRun_U.setProperty("value", 0.5)
        self.doubleSpinBox_singleRun_U.setObjectName(_fromUtf8("doubleSpinBox_singleRun_U"))
        self.gridLayout_singleRun.addWidget(self.doubleSpinBox_singleRun_U, 0, 1, 1, 1)
        self.label_6 = QtGui.QLabel(self.gridLayoutWidget_4)
        self.label_6.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.gridLayout_singleRun.addWidget(self.label_6, 3, 0, 1, 1)
        self.doubleSpinBox_singleRun_tsr = QtGui.QDoubleSpinBox(self.gridLayoutWidget_4)
        self.doubleSpinBox_singleRun_tsr.setMaximum(7.0)
        self.doubleSpinBox_singleRun_tsr.setSingleStep(0.1)
        self.doubleSpinBox_singleRun_tsr.setProperty("value", 1.9)
        self.doubleSpinBox_singleRun_tsr.setObjectName(_fromUtf8("doubleSpinBox_singleRun_tsr"))
        self.gridLayout_singleRun.addWidget(self.doubleSpinBox_singleRun_tsr, 3, 1, 1, 1)
        self.label_10 = QtGui.QLabel(self.gridLayoutWidget_4)
        self.label_10.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.gridLayout_singleRun.addWidget(self.label_10, 4, 0, 1, 1)
        self.label_33 = QtGui.QLabel(self.gridLayoutWidget_4)
        self.label_33.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_33.setObjectName(_fromUtf8("label_33"))
        self.gridLayout_singleRun.addWidget(self.label_33, 5, 0, 1, 1)
        self.doubleSpinBox_singleRun_z_H = QtGui.QDoubleSpinBox(self.gridLayoutWidget_4)
        self.doubleSpinBox_singleRun_z_H.setSingleStep(0.125)
        self.doubleSpinBox_singleRun_z_H.setProperty("value", 0.25)
        self.doubleSpinBox_singleRun_z_H.setObjectName(_fromUtf8("doubleSpinBox_singleRun_z_H"))
        self.gridLayout_singleRun.addWidget(self.doubleSpinBox_singleRun_z_H, 5, 1, 1, 1)
        self.toolButtonOpenShakedown = QtGui.QToolButton(self.gridLayoutWidget_4)
        self.toolButtonOpenShakedown.setObjectName(_fromUtf8("toolButtonOpenShakedown"))
        self.gridLayout_singleRun.addWidget(self.toolButtonOpenShakedown, 0, 2, 1, 1)
        self.doubleSpinBox_turbineRadius = QtGui.QDoubleSpinBox(self.gridLayoutWidget_4)
        self.doubleSpinBox_turbineRadius.setDecimals(4)
        self.doubleSpinBox_turbineRadius.setSingleStep(0.01)
        self.doubleSpinBox_turbineRadius.setProperty("value", 0.5)
        self.doubleSpinBox_turbineRadius.setObjectName(_fromUtf8("doubleSpinBox_turbineRadius"))
        self.gridLayout_singleRun.addWidget(self.doubleSpinBox_turbineRadius, 1, 1, 1, 1)
        self.label_35 = QtGui.QLabel(self.gridLayoutWidget_4)
        self.label_35.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_35.setObjectName(_fromUtf8("label_35"))
        self.gridLayout_singleRun.addWidget(self.label_35, 2, 0, 1, 1)
        self.doubleSpinBox_turbineHeight = QtGui.QDoubleSpinBox(self.gridLayoutWidget_4)
        self.doubleSpinBox_turbineHeight.setDecimals(4)
        self.doubleSpinBox_turbineHeight.setSingleStep(0.1)
        self.doubleSpinBox_turbineHeight.setProperty("value", 1.0)
        self.doubleSpinBox_turbineHeight.setObjectName(_fromUtf8("doubleSpinBox_turbineHeight"))
        self.gridLayout_singleRun.addWidget(self.doubleSpinBox_turbineHeight, 2, 1, 1, 1)
        self.checkBox_singleRunVectrino = QtGui.QCheckBox(self.gridLayoutWidget_4)
        self.checkBox_singleRunVectrino.setObjectName(_fromUtf8("checkBox_singleRunVectrino"))
        self.gridLayout_singleRun.addWidget(self.checkBox_singleRunVectrino, 6, 1, 1, 1)
        self.checkBox_singleRunFBG = QtGui.QCheckBox(self.gridLayoutWidget_4)
        self.checkBox_singleRunFBG.setObjectName(_fromUtf8("checkBox_singleRunFBG"))
        self.gridLayout_singleRun.addWidget(self.checkBox_singleRunFBG, 7, 1, 1, 1)
        self.tabWidgetMode.addTab(self.tabSingleRun, _fromUtf8(""))
        self.tabTestPlan = QtGui.QWidget()
        self.tabTestPlan.setObjectName(_fromUtf8("tabTestPlan"))
        self.gridLayout_9 = QtGui.QGridLayout(self.tabTestPlan)
        self.gridLayout_9.setObjectName(_fromUtf8("gridLayout_9"))
        self.label_32 = QtGui.QLabel(self.tabTestPlan)
        self.label_32.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_32.setObjectName(_fromUtf8("label_32"))
        self.gridLayout_9.addWidget(self.label_32, 0, 0, 1, 1)
        self.comboBox_testPlanSection = QtGui.QComboBox(self.tabTestPlan)
        self.comboBox_testPlanSection.setMaximumSize(QtCore.QSize(100, 16777215))
        self.comboBox_testPlanSection.setObjectName(_fromUtf8("comboBox_testPlanSection"))
        self.gridLayout_9.addWidget(self.comboBox_testPlanSection, 0, 1, 1, 1)
        self.toolButtonOpenSection = QtGui.QToolButton(self.tabTestPlan)
        self.toolButtonOpenSection.setObjectName(_fromUtf8("toolButtonOpenSection"))
        self.gridLayout_9.addWidget(self.toolButtonOpenSection, 0, 2, 1, 1)
        self.tableWidgetTestPlan = QtGui.QTableWidget(self.tabTestPlan)
        self.tableWidgetTestPlan.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.tableWidgetTestPlan.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.tableWidgetTestPlan.setEditTriggers(QtGui.QAbstractItemView.NoEditTriggers)
        self.tableWidgetTestPlan.setAlternatingRowColors(False)
        self.tableWidgetTestPlan.setSelectionMode(QtGui.QAbstractItemView.NoSelection)
        self.tableWidgetTestPlan.setTextElideMode(QtCore.Qt.ElideMiddle)
        self.tableWidgetTestPlan.setObjectName(_fromUtf8("tableWidgetTestPlan"))
        self.tableWidgetTestPlan.setColumnCount(6)
        self.tableWidgetTestPlan.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter|QtCore.Qt.AlignCenter)
        self.tableWidgetTestPlan.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidgetTestPlan.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidgetTestPlan.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidgetTestPlan.setHorizontalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidgetTestPlan.setHorizontalHeaderItem(4, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidgetTestPlan.setHorizontalHeaderItem(5, item)
        self.tableWidgetTestPlan.horizontalHeader().setDefaultSectionSize(57)
        self.tableWidgetTestPlan.horizontalHeader().setMinimumSectionSize(20)
        self.tableWidgetTestPlan.horizontalHeader().setStretchLastSection(False)
        self.tableWidgetTestPlan.verticalHeader().setVisible(False)
        self.tableWidgetTestPlan.verticalHeader().setDefaultSectionSize(15)
        self.tableWidgetTestPlan.verticalHeader().setHighlightSections(False)
        self.tableWidgetTestPlan.verticalHeader().setMinimumSectionSize(15)
        self.tableWidgetTestPlan.verticalHeader().setStretchLastSection(False)
        self.gridLayout_9.addWidget(self.tableWidgetTestPlan, 1, 0, 1, 3)
        self.tabWidgetMode.addTab(self.tabTestPlan, _fromUtf8(""))
        self.tabProcessing = QtGui.QWidget()
        self.tabProcessing.setObjectName(_fromUtf8("tabProcessing"))
        self.groupBox = QtGui.QGroupBox(self.tabProcessing)
        self.groupBox.setGeometry(QtCore.QRect(200, 10, 171, 111))
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.gridLayoutWidget_5 = QtGui.QWidget(self.groupBox)
        self.gridLayoutWidget_5.setGeometry(QtCore.QRect(10, 20, 151, 80))
        self.gridLayoutWidget_5.setObjectName(_fromUtf8("gridLayoutWidget_5"))
        self.gridLayout_5 = QtGui.QGridLayout(self.gridLayoutWidget_5)
        self.gridLayout_5.setMargin(0)
        self.gridLayout_5.setObjectName(_fromUtf8("gridLayout_5"))
        self.label_20 = QtGui.QLabel(self.gridLayoutWidget_5)
        self.label_20.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_20.setObjectName(_fromUtf8("label_20"))
        self.gridLayout_5.addWidget(self.label_20, 1, 0, 1, 1)
        self.label_24 = QtGui.QLabel(self.gridLayoutWidget_5)
        self.label_24.setObjectName(_fromUtf8("label_24"))
        self.gridLayout_5.addWidget(self.label_24, 1, 1, 1, 1)
        self.label_25 = QtGui.QLabel(self.gridLayoutWidget_5)
        self.label_25.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_25.setObjectName(_fromUtf8("label_25"))
        self.gridLayout_5.addWidget(self.label_25, 2, 0, 1, 1)
        self.label_29 = QtGui.QLabel(self.gridLayoutWidget_5)
        self.label_29.setObjectName(_fromUtf8("label_29"))
        self.gridLayout_5.addWidget(self.label_29, 2, 1, 1, 1)
        self.label_30 = QtGui.QLabel(self.gridLayoutWidget_5)
        self.label_30.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_30.setObjectName(_fromUtf8("label_30"))
        self.gridLayout_5.addWidget(self.label_30, 0, 0, 1, 1)
        self.label_31 = QtGui.QLabel(self.gridLayoutWidget_5)
        self.label_31.setObjectName(_fromUtf8("label_31"))
        self.gridLayout_5.addWidget(self.label_31, 0, 1, 1, 1)
        self.groupBox_2 = QtGui.QGroupBox(self.tabProcessing)
        self.groupBox_2.setGeometry(QtCore.QRect(10, 10, 181, 141))
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.gridLayoutWidget_2 = QtGui.QWidget(self.groupBox_2)
        self.gridLayoutWidget_2.setGeometry(QtCore.QRect(10, 20, 161, 111))
        self.gridLayoutWidget_2.setObjectName(_fromUtf8("gridLayoutWidget_2"))
        self.gridLayout_2 = QtGui.QGridLayout(self.gridLayoutWidget_2)
        self.gridLayout_2.setMargin(0)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.label_23 = QtGui.QLabel(self.gridLayoutWidget_2)
        self.label_23.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_23.setObjectName(_fromUtf8("label_23"))
        self.gridLayout_2.addWidget(self.label_23, 1, 0, 1, 1)
        self.comboBox_process_nrun = QtGui.QComboBox(self.gridLayoutWidget_2)
        self.comboBox_process_nrun.setObjectName(_fromUtf8("comboBox_process_nrun"))
        self.gridLayout_2.addWidget(self.comboBox_process_nrun, 1, 1, 1, 1)
        self.label_21 = QtGui.QLabel(self.gridLayoutWidget_2)
        self.label_21.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_21.setObjectName(_fromUtf8("label_21"))
        self.gridLayout_2.addWidget(self.label_21, 2, 0, 1, 1)
        self.label_22 = QtGui.QLabel(self.gridLayoutWidget_2)
        self.label_22.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_22.setObjectName(_fromUtf8("label_22"))
        self.gridLayout_2.addWidget(self.label_22, 3, 0, 1, 1)
        self.doubleSpinBox_t1 = QtGui.QDoubleSpinBox(self.gridLayoutWidget_2)
        self.doubleSpinBox_t1.setObjectName(_fromUtf8("doubleSpinBox_t1"))
        self.gridLayout_2.addWidget(self.doubleSpinBox_t1, 2, 1, 1, 1)
        self.doubleSpinBox_t2 = QtGui.QDoubleSpinBox(self.gridLayoutWidget_2)
        self.doubleSpinBox_t2.setObjectName(_fromUtf8("doubleSpinBox_t2"))
        self.gridLayout_2.addWidget(self.doubleSpinBox_t2, 3, 1, 1, 1)
        self.label_28 = QtGui.QLabel(self.gridLayoutWidget_2)
        self.label_28.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_28.setObjectName(_fromUtf8("label_28"))
        self.gridLayout_2.addWidget(self.label_28, 0, 0, 1, 1)
        self.comboBox_process_section = QtGui.QComboBox(self.gridLayoutWidget_2)
        self.comboBox_process_section.setObjectName(_fromUtf8("comboBox_process_section"))
        self.gridLayout_2.addWidget(self.comboBox_process_section, 0, 1, 1, 1)
        self.checkBox = QtGui.QCheckBox(self.tabProcessing)
        self.checkBox.setGeometry(QtCore.QRect(150, 250, 76, 17))
        self.checkBox.setObjectName(_fromUtf8("checkBox"))
        self.commandLinkButton_process = QtGui.QCommandLinkButton(self.tabProcessing)
        self.commandLinkButton_process.setGeometry(QtCore.QRect(280, 230, 91, 41))
        self.commandLinkButton_process.setObjectName(_fromUtf8("commandLinkButton_process"))
        self.tabWidgetMode.addTab(self.tabProcessing, _fromUtf8(""))
        self.gridLayout_4.addWidget(self.tabWidgetMode, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1168, 21))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuFile = QtGui.QMenu(self.menubar)
        self.menuFile.setObjectName(_fromUtf8("menuFile"))
        self.menuHoming = QtGui.QMenu(self.menubar)
        self.menuHoming.setObjectName(_fromUtf8("menuHoming"))
        self.menuView = QtGui.QMenu(self.menubar)
        self.menuView.setObjectName(_fromUtf8("menuView"))
        self.menuSetings = QtGui.QMenu(self.menubar)
        self.menuSetings.setObjectName(_fromUtf8("menuSetings"))
        self.menuTest_Plan = QtGui.QMenu(self.menubar)
        self.menuTest_Plan.setObjectName(_fromUtf8("menuTest_Plan"))
        self.menuHelp = QtGui.QMenu(self.menubar)
        self.menuHelp.setObjectName(_fromUtf8("menuHelp"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)
        self.toolBar = QtGui.QToolBar(MainWindow)
        self.toolBar.setToolTip(_fromUtf8(""))
        self.toolBar.setObjectName(_fromUtf8("toolBar"))
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.toolBar_DAQ = QtGui.QToolBar(MainWindow)
        self.toolBar_DAQ.setObjectName(_fromUtf8("toolBar_DAQ"))
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar_DAQ)
        self.toolBar_directory = QtGui.QToolBar(MainWindow)
        self.toolBar_directory.setObjectName(_fromUtf8("toolBar_directory"))
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar_directory)
        self.actionStart = QtGui.QAction(MainWindow)
        self.actionStart.setCheckable(True)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/play.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionStart.setIcon(icon1)
        self.actionStart.setObjectName(_fromUtf8("actionStart"))
        self.actionQuit = QtGui.QAction(MainWindow)
        self.actionQuit.setObjectName(_fromUtf8("actionQuit"))
        self.actionCOM_Port = QtGui.QAction(MainWindow)
        self.actionCOM_Port.setObjectName(_fromUtf8("actionCOM_Port"))
        self.actionHome_Tow = QtGui.QAction(MainWindow)
        self.actionHome_Tow.setObjectName(_fromUtf8("actionHome_Tow"))
        self.actionEnable_Tow = QtGui.QAction(MainWindow)
        self.actionEnable_Tow.setCheckable(True)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/tow_icon_b.ico")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionEnable_Tow.setIcon(icon2)
        self.actionEnable_Tow.setObjectName(_fromUtf8("actionEnable_Tow"))
        self.actionHome_Turbine = QtGui.QAction(MainWindow)
        self.actionHome_Turbine.setObjectName(_fromUtf8("actionHome_Turbine"))
        self.actionHome_y = QtGui.QAction(MainWindow)
        self.actionHome_y.setObjectName(_fromUtf8("actionHome_y"))
        self.actionHome_z = QtGui.QAction(MainWindow)
        self.actionHome_z.setObjectName(_fromUtf8("actionHome_z"))
        self.actionEdit_Configuration = QtGui.QAction(MainWindow)
        self.actionEdit_Configuration.setObjectName(_fromUtf8("actionEdit_Configuration"))
        self.actionMonitor_NI = QtGui.QAction(MainWindow)
        self.actionMonitor_NI.setCheckable(True)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/max.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionMonitor_NI.setIcon(icon3)
        self.actionMonitor_NI.setObjectName(_fromUtf8("actionMonitor_NI"))
        self.actionMonitor_Vectrino = QtGui.QAction(MainWindow)
        self.actionMonitor_Vectrino.setCheckable(True)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/vectrino.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionMonitor_Vectrino.setIcon(icon4)
        self.actionMonitor_Vectrino.setObjectName(_fromUtf8("actionMonitor_Vectrino"))
        self.actionVectrino = QtGui.QAction(MainWindow)
        self.actionVectrino.setObjectName(_fromUtf8("actionVectrino"))
        self.actionTurbine_Characteristics = QtGui.QAction(MainWindow)
        self.actionTurbine_Characteristics.setObjectName(_fromUtf8("actionTurbine_Characteristics"))
        self.actionImportTestPlan = QtGui.QAction(MainWindow)
        self.actionImportTestPlan.setObjectName(_fromUtf8("actionImportTestPlan"))
        self.actionAbort = QtGui.QAction(MainWindow)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/agt_stop.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionAbort.setIcon(icon5)
        self.actionAbort.setObjectName(_fromUtf8("actionAbort"))
        self.actionEnable_Turbine = QtGui.QAction(MainWindow)
        self.actionEnable_Turbine.setCheckable(True)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/turbine.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionEnable_Turbine.setIcon(icon6)
        self.actionEnable_Turbine.setObjectName(_fromUtf8("actionEnable_Turbine"))
        self.actionEnable_y = QtGui.QAction(MainWindow)
        self.actionEnable_y.setCheckable(True)
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/agt_back.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionEnable_y.setIcon(icon7)
        self.actionEnable_y.setObjectName(_fromUtf8("actionEnable_y"))
        self.actionEnable_z = QtGui.QAction(MainWindow)
        self.actionEnable_z.setCheckable(True)
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/up.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionEnable_z.setIcon(icon8)
        self.actionEnable_z.setObjectName(_fromUtf8("actionEnable_z"))
        self.actionEnable_All = QtGui.QAction(MainWindow)
        self.actionEnable_All.setCheckable(True)
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/button_ok.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionEnable_All.setIcon(icon9)
        self.actionEnable_All.setObjectName(_fromUtf8("actionEnable_All"))
        self.actionMonitor_ACS = QtGui.QAction(MainWindow)
        self.actionMonitor_ACS.setCheckable(True)
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/acs.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionMonitor_ACS.setIcon(icon10)
        self.actionMonitor_ACS.setObjectName(_fromUtf8("actionMonitor_ACS"))
        self.actionAbout = QtGui.QAction(MainWindow)
        self.actionAbout.setObjectName(_fromUtf8("actionAbout"))
        self.actionMonitor_FBG = QtGui.QAction(MainWindow)
        self.actionMonitor_FBG.setCheckable(True)
        icon11 = QtGui.QIcon()
        icon11.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/micron.svg")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionMonitor_FBG.setIcon(icon11)
        self.actionMonitor_FBG.setObjectName(_fromUtf8("actionMonitor_FBG"))
        self.actionNI_Signals = QtGui.QAction(MainWindow)
        self.actionNI_Signals.setCheckable(True)
        self.actionNI_Signals.setChecked(True)
        self.actionNI_Signals.setObjectName(_fromUtf8("actionNI_Signals"))
        self.actionVectrino_View = QtGui.QAction(MainWindow)
        self.actionVectrino_View.setCheckable(True)
        self.actionVectrino_View.setChecked(True)
        self.actionVectrino_View.setObjectName(_fromUtf8("actionVectrino_View"))
        self.actionFBG = QtGui.QAction(MainWindow)
        self.actionFBG.setCheckable(True)
        self.actionFBG.setChecked(True)
        self.actionFBG.setObjectName(_fromUtf8("actionFBG"))
        self.menuFile.addAction(self.actionQuit)
        self.menuHoming.addAction(self.actionHome_Tow)
        self.menuHoming.addAction(self.actionHome_Turbine)
        self.menuHoming.addAction(self.actionHome_y)
        self.menuHoming.addAction(self.actionHome_z)
        self.menuView.addAction(self.actionNI_Signals)
        self.menuView.addAction(self.actionVectrino_View)
        self.menuView.addAction(self.actionFBG)
        self.menuSetings.addAction(self.actionVectrino)
        self.menuSetings.addAction(self.actionTurbine_Characteristics)
        self.menuTest_Plan.addAction(self.actionImportTestPlan)
        self.menuHelp.addAction(self.actionAbout)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuView.menuAction())
        self.menubar.addAction(self.menuSetings.menuAction())
        self.menubar.addAction(self.menuHoming.menuAction())
        self.menubar.addAction(self.menuTest_Plan.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())
        self.toolBar.addAction(self.actionStart)
        self.toolBar.addAction(self.actionAbort)
        self.toolBar_DAQ.addAction(self.actionMonitor_ACS)
        self.toolBar_DAQ.addAction(self.actionMonitor_NI)
        self.toolBar_DAQ.addAction(self.actionMonitor_Vectrino)
        self.toolBar_DAQ.addAction(self.actionMonitor_FBG)

        self.retranslateUi(MainWindow)
        self.tabWidgetMode.setCurrentIndex(0)
        QtCore.QObject.connect(self.actionNI_Signals, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.dockWidgetNISignals.setVisible)
        QtCore.QObject.connect(self.actionVectrino_View, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.dockWidgetVectrino.setVisible)
        QtCore.QObject.connect(self.dockWidgetNISignals, QtCore.SIGNAL(_fromUtf8("visibilityChanged(bool)")), self.actionNI_Signals.setChecked)
        QtCore.QObject.connect(self.dockWidgetVectrino, QtCore.SIGNAL(_fromUtf8("visibilityChanged(bool)")), self.actionVectrino_View.setChecked)
        QtCore.QObject.connect(self.actionFBG, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.dockWidget_FBG.setVisible)
        QtCore.QObject.connect(self.dockWidget_FBG, QtCore.SIGNAL(_fromUtf8("visibilityChanged(bool)")), self.actionFBG.setChecked)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "TurbineDAQ", None))
        self.dockWidgetNISignals.setWindowTitle(_translate("MainWindow", "NI Signals", None))
        self.label.setText(_translate("MainWindow", "            Torque (Nm)", None))
        self.label_2.setText(_translate("MainWindow", "            Drag (N)", None))
        self.label_12.setText(_translate("MainWindow", "             Drag Left (N)", None))
        self.label_13.setText(_translate("MainWindow", "            Drag Right (N)", None))
        self.label_16.setText(_translate("MainWindow", "           Turbine RPM", None))
        self.dockWidgetVectrino.setWindowTitle(_translate("MainWindow", "Vectrino", None))
        self.label_vecu.setText(_translate("MainWindow", "            u (m/s)", None))
        self.label_11.setText(_translate("MainWindow", "          v (m/s)", None))
        self.label_14.setText(_translate("MainWindow", "          w (m/s)", None))
        self.label_15.setText(_translate("MainWindow", "            Correlation (%)", None))
        self.label_5.setText(_translate("MainWindow", "            SNR (dB)", None))
        self.dockWidget_FBG.setWindowTitle(_translate("MainWindow", "FBG", None))
        self.label_FBG_1.setText(_translate("MainWindow", "             Sensor 1", None))
        self.label_FBG_2.setText(_translate("MainWindow", "            Sensor 2", None))
        self.label_FBG_3.setText(_translate("MainWindow", "            Sensor 3", None))
        self.label_FBG_4.setText(_translate("MainWindow", "            Sensor 4", None))
        self.label_FBG_5.setText(_translate("MainWindow", "           Sensor 5", None))
        self.dockWidget_acscontrol.setWindowTitle(_translate("MainWindow", "ACS Controller", None))
        item = self.tableWidget_acs.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Axis", None))
        item = self.tableWidget_acs.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Enabled?", None))
        item = self.tableWidget_acs.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Home #", None))
        item = self.tableWidget_acs.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "RPOS", None))
        item = self.tableWidget_acs.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "FPOS", None))
        item = self.tableWidget_acs.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "FVEL", None))
        __sortingEnabled = self.tableWidget_acs.isSortingEnabled()
        self.tableWidget_acs.setSortingEnabled(False)
        item = self.tableWidget_acs.item(0, 0)
        item.setText(_translate("MainWindow", "tow", None))
        item = self.tableWidget_acs.item(1, 0)
        item.setText(_translate("MainWindow", "turbine", None))
        item = self.tableWidget_acs.item(2, 0)
        item.setText(_translate("MainWindow", "y", None))
        item = self.tableWidget_acs.item(3, 0)
        item.setText(_translate("MainWindow", "z", None))
        self.tableWidget_acs.setSortingEnabled(__sortingEnabled)
        self.label_26.setText(_translate("MainWindow", "             Tow Speed (m/s)", None))
        self.label_27.setText(_translate("MainWindow", "           Turbine RPM", None))
        self.label_34.setText(_translate("MainWindow", "R (m)", None))
        self.label_3.setText(_translate("MainWindow", "Tow Speed (m/s)", None))
        self.label_6.setText(_translate("MainWindow", "Tip Speed Ratio", None))
        self.label_10.setText(_translate("MainWindow", "y/R", None))
        self.label_33.setText(_translate("MainWindow", "z/H", None))
        self.toolButtonOpenShakedown.setText(_translate("MainWindow", "...", None))
        self.label_35.setText(_translate("MainWindow", "H (m)", None))
        self.checkBox_singleRunVectrino.setText(_translate("MainWindow", "Vectrino", None))
        self.checkBox_singleRunFBG.setText(_translate("MainWindow", "FBG", None))
        self.tabWidgetMode.setTabText(self.tabWidgetMode.indexOf(self.tabSingleRun), _translate("MainWindow", "Shakedown Run", None))
        self.label_32.setText(_translate("MainWindow", "Section", None))
        self.toolButtonOpenSection.setText(_translate("MainWindow", "...", None))
        item = self.tableWidgetTestPlan.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Run", None))
        item = self.tableWidgetTestPlan.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "U (m/s)", None))
        item = self.tableWidgetTestPlan.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "λ", None))
        item = self.tableWidgetTestPlan.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "y/R", None))
        item = self.tableWidgetTestPlan.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "z/H", None))
        item = self.tableWidgetTestPlan.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "Done?", None))
        self.tabWidgetMode.setTabText(self.tabWidgetMode.indexOf(self.tabTestPlan), _translate("MainWindow", "Test Plan", None))
        self.groupBox.setTitle(_translate("MainWindow", "Results", None))
        self.label_20.setText(_translate("MainWindow", "C_P", None))
        self.label_24.setText(_translate("MainWindow", "TextLabel", None))
        self.label_25.setText(_translate("MainWindow", "C_D", None))
        self.label_29.setText(_translate("MainWindow", "TextLabel", None))
        self.label_30.setText(_translate("MainWindow", "TSR", None))
        self.label_31.setText(_translate("MainWindow", "TextLabel", None))
        self.groupBox_2.setTitle(_translate("MainWindow", "Parameters", None))
        self.label_23.setText(_translate("MainWindow", "Run", None))
        self.label_21.setText(_translate("MainWindow", "Start Time (s)", None))
        self.label_22.setText(_translate("MainWindow", "End Time (s)", None))
        self.label_28.setText(_translate("MainWindow", "Section", None))
        self.checkBox.setText(_translate("MainWindow", "Plot?", None))
        self.commandLinkButton_process.setText(_translate("MainWindow", "Process", None))
        self.tabWidgetMode.setTabText(self.tabWidgetMode.indexOf(self.tabProcessing), _translate("MainWindow", "Processing", None))
        self.menuFile.setTitle(_translate("MainWindow", "File", None))
        self.menuHoming.setTitle(_translate("MainWindow", "Homing", None))
        self.menuView.setTitle(_translate("MainWindow", "View", None))
        self.menuSetings.setTitle(_translate("MainWindow", "Settings", None))
        self.menuTest_Plan.setTitle(_translate("MainWindow", "Test Plan", None))
        self.menuHelp.setTitle(_translate("MainWindow", "Help", None))
        self.toolBar.setWindowTitle(_translate("MainWindow", "toolBar", None))
        self.toolBar_DAQ.setWindowTitle(_translate("MainWindow", "toolBar_2", None))
        self.toolBar_directory.setWindowTitle(_translate("MainWindow", "toolBar_2", None))
        self.actionStart.setText(_translate("MainWindow", "Start", None))
        self.actionQuit.setText(_translate("MainWindow", "Quit", None))
        self.actionCOM_Port.setText(_translate("MainWindow", "COM Port", None))
        self.actionHome_Tow.setText(_translate("MainWindow", "Home Tow Axis", None))
        self.actionEnable_Tow.setText(_translate("MainWindow", "Enable Tow", None))
        self.actionEnable_Tow.setToolTip(_translate("MainWindow", "Tow Axis Enable", None))
        self.actionHome_Turbine.setText(_translate("MainWindow", "Home Turbine Axis", None))
        self.actionHome_y.setText(_translate("MainWindow", "Home y-axis", None))
        self.actionHome_z.setText(_translate("MainWindow", "Home z-axis", None))
        self.actionEdit_Configuration.setText(_translate("MainWindow", "Edit Configuration...", None))
        self.actionMonitor_NI.setText(_translate("MainWindow", "Monitor NI Signals", None))
        self.actionMonitor_NI.setToolTip(_translate("MainWindow", "Monitor NI Signals", None))
        self.actionMonitor_Vectrino.setText(_translate("MainWindow", "Monitor Vectrino", None))
        self.actionMonitor_Vectrino.setToolTip(_translate("MainWindow", "Monitor Vectrino Signals", None))
        self.actionVectrino.setText(_translate("MainWindow", "Vectrino...", None))
        self.actionTurbine_Characteristics.setText(_translate("MainWindow", "Turbine Characteristics...", None))
        self.actionImportTestPlan.setText(_translate("MainWindow", "Reload", None))
        self.actionAbort.setText(_translate("MainWindow", "Abort", None))
        self.actionAbort.setToolTip(_translate("MainWindow", "Stop immediately and abort run", None))
        self.actionEnable_Turbine.setText(_translate("MainWindow", "Enable Turbine", None))
        self.actionEnable_y.setText(_translate("MainWindow", "Enable y", None))
        self.actionEnable_z.setText(_translate("MainWindow", "Enable z", None))
        self.actionEnable_All.setText(_translate("MainWindow", "Enable All", None))
        self.actionEnable_All.setToolTip(_translate("MainWindow", "Enable all axes", None))
        self.actionMonitor_ACS.setText(_translate("MainWindow", "Monitor ACS", None))
        self.actionMonitor_ACS.setToolTip(_translate("MainWindow", "Monitor values in ACS controller", None))
        self.actionAbout.setText(_translate("MainWindow", "About", None))
        self.actionMonitor_FBG.setText(_translate("MainWindow", "Monitor FBG", None))
        self.actionMonitor_FBG.setToolTip(_translate("MainWindow", "Monitor FBG...", None))
        self.actionNI_Signals.setText(_translate("MainWindow", "NI Signals", None))
        self.actionVectrino_View.setText(_translate("MainWindow", "Vectrino", None))
        self.actionFBG.setText(_translate("MainWindow", "FBG", None))

from guiqwt.plot import CurveWidget
import resources_rc
