# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created: Tue Sep 24 23:04:53 2013
#      by: PyQt4 UI code generator 4.9.5
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(1126, 961)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/turbine.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.tabWidgetMode = QtGui.QTabWidget(self.centralwidget)
        self.tabWidgetMode.setGeometry(QtCore.QRect(10, 10, 381, 371))
        self.tabWidgetMode.setObjectName(_fromUtf8("tabWidgetMode"))
        self.tabTareDrag = QtGui.QWidget()
        self.tabTareDrag.setObjectName(_fromUtf8("tabTareDrag"))
        self.gridLayoutWidget_3 = QtGui.QWidget(self.tabTareDrag)
        self.gridLayoutWidget_3.setGeometry(QtCore.QRect(10, 10, 151, 111))
        self.gridLayoutWidget_3.setObjectName(_fromUtf8("gridLayoutWidget_3"))
        self.gridLayout_3 = QtGui.QGridLayout(self.gridLayoutWidget_3)
        self.gridLayout_3.setMargin(0)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.doubleSpinBox_tareDragStepU = QtGui.QDoubleSpinBox(self.gridLayoutWidget_3)
        self.doubleSpinBox_tareDragStepU.setProperty("value", 0.5)
        self.doubleSpinBox_tareDragStepU.setObjectName(_fromUtf8("doubleSpinBox_tareDragStepU"))
        self.gridLayout_3.addWidget(self.doubleSpinBox_tareDragStepU, 2, 1, 1, 1)
        self.label_19 = QtGui.QLabel(self.gridLayoutWidget_3)
        self.label_19.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_19.setObjectName(_fromUtf8("label_19"))
        self.gridLayout_3.addWidget(self.label_19, 1, 0, 1, 1)
        self.label_18 = QtGui.QLabel(self.gridLayoutWidget_3)
        self.label_18.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_18.setObjectName(_fromUtf8("label_18"))
        self.gridLayout_3.addWidget(self.label_18, 2, 0, 1, 1)
        self.doubleSpinBox_tareDragEndU = QtGui.QDoubleSpinBox(self.gridLayoutWidget_3)
        self.doubleSpinBox_tareDragEndU.setProperty("value", 0.1)
        self.doubleSpinBox_tareDragEndU.setObjectName(_fromUtf8("doubleSpinBox_tareDragEndU"))
        self.gridLayout_3.addWidget(self.doubleSpinBox_tareDragEndU, 1, 1, 1, 1)
        self.doubleSpinBox_tareDragStartU = QtGui.QDoubleSpinBox(self.gridLayoutWidget_3)
        self.doubleSpinBox_tareDragStartU.setProperty("value", 1.0)
        self.doubleSpinBox_tareDragStartU.setObjectName(_fromUtf8("doubleSpinBox_tareDragStartU"))
        self.gridLayout_3.addWidget(self.doubleSpinBox_tareDragStartU, 0, 1, 1, 1)
        self.label_17 = QtGui.QLabel(self.gridLayoutWidget_3)
        self.label_17.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_17.setObjectName(_fromUtf8("label_17"))
        self.gridLayout_3.addWidget(self.label_17, 0, 0, 1, 1)
        self.tabWidgetMode.addTab(self.tabTareDrag, _fromUtf8(""))
        self.tabTareTorque = QtGui.QWidget()
        self.tabTareTorque.setObjectName(_fromUtf8("tabTareTorque"))
        self.gridLayoutWidget = QtGui.QWidget(self.tabTareTorque)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(10, 10, 201, 151))
        self.gridLayoutWidget.setObjectName(_fromUtf8("gridLayoutWidget"))
        self.gridLayout = QtGui.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setMargin(0)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.doubleSpinBox_tareTorqueStepTsr = QtGui.QDoubleSpinBox(self.gridLayoutWidget)
        self.doubleSpinBox_tareTorqueStepTsr.setObjectName(_fromUtf8("doubleSpinBox_tareTorqueStepTsr"))
        self.gridLayout.addWidget(self.doubleSpinBox_tareTorqueStepTsr, 3, 1, 1, 1)
        self.label_9 = QtGui.QLabel(self.gridLayoutWidget)
        self.label_9.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.gridLayout.addWidget(self.label_9, 0, 0, 1, 1)
        self.doubleSpinBox_tareTorqueRefU = QtGui.QDoubleSpinBox(self.gridLayoutWidget)
        self.doubleSpinBox_tareTorqueRefU.setProperty("value", 1.0)
        self.doubleSpinBox_tareTorqueRefU.setObjectName(_fromUtf8("doubleSpinBox_tareTorqueRefU"))
        self.gridLayout.addWidget(self.doubleSpinBox_tareTorqueRefU, 0, 1, 1, 1)
        self.doubleSpinBox_tareTorqueStartTsr = QtGui.QDoubleSpinBox(self.gridLayoutWidget)
        self.doubleSpinBox_tareTorqueStartTsr.setProperty("value", 0.1)
        self.doubleSpinBox_tareTorqueStartTsr.setObjectName(_fromUtf8("doubleSpinBox_tareTorqueStartTsr"))
        self.gridLayout.addWidget(self.doubleSpinBox_tareTorqueStartTsr, 1, 1, 1, 1)
        self.label_8 = QtGui.QLabel(self.gridLayoutWidget)
        self.label_8.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.gridLayout.addWidget(self.label_8, 2, 0, 1, 1)
        self.label_7 = QtGui.QLabel(self.gridLayoutWidget)
        self.label_7.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.gridLayout.addWidget(self.label_7, 1, 0, 1, 1)
        self.doubleSpinBox_tareTorqueEndTsr = QtGui.QDoubleSpinBox(self.gridLayoutWidget)
        self.doubleSpinBox_tareTorqueEndTsr.setProperty("value", 3.1)
        self.doubleSpinBox_tareTorqueEndTsr.setObjectName(_fromUtf8("doubleSpinBox_tareTorqueEndTsr"))
        self.gridLayout.addWidget(self.doubleSpinBox_tareTorqueEndTsr, 2, 1, 1, 1)
        self.label_4 = QtGui.QLabel(self.gridLayoutWidget)
        self.label_4.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.gridLayout.addWidget(self.label_4, 3, 0, 1, 1)
        self.label_startTsrRpm = QtGui.QLabel(self.gridLayoutWidget)
        self.label_startTsrRpm.setObjectName(_fromUtf8("label_startTsrRpm"))
        self.gridLayout.addWidget(self.label_startTsrRpm, 1, 2, 1, 1)
        self.label_stopTsrRpm = QtGui.QLabel(self.gridLayoutWidget)
        self.label_stopTsrRpm.setObjectName(_fromUtf8("label_stopTsrRpm"))
        self.gridLayout.addWidget(self.label_stopTsrRpm, 2, 2, 1, 1)
        self.tabWidgetMode.addTab(self.tabTareTorque, _fromUtf8(""))
        self.tabSingleRun = QtGui.QWidget()
        self.tabSingleRun.setObjectName(_fromUtf8("tabSingleRun"))
        self.gridLayoutWidget_4 = QtGui.QWidget(self.tabSingleRun)
        self.gridLayoutWidget_4.setGeometry(QtCore.QRect(10, 10, 211, 131))
        self.gridLayoutWidget_4.setObjectName(_fromUtf8("gridLayoutWidget_4"))
        self.gridLayout_4 = QtGui.QGridLayout(self.gridLayoutWidget_4)
        self.gridLayout_4.setMargin(0)
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.doubleSpinBox_singleRun_y_R = QtGui.QDoubleSpinBox(self.gridLayoutWidget_4)
        self.doubleSpinBox_singleRun_y_R.setObjectName(_fromUtf8("doubleSpinBox_singleRun_y_R"))
        self.gridLayout_4.addWidget(self.doubleSpinBox_singleRun_y_R, 2, 1, 1, 1)
        self.label_3 = QtGui.QLabel(self.gridLayoutWidget_4)
        self.label_3.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout_4.addWidget(self.label_3, 0, 0, 1, 1)
        self.doubleSpinBox_singleRun_U = QtGui.QDoubleSpinBox(self.gridLayoutWidget_4)
        self.doubleSpinBox_singleRun_U.setMaximum(2.0)
        self.doubleSpinBox_singleRun_U.setSingleStep(0.1)
        self.doubleSpinBox_singleRun_U.setProperty("value", 1.0)
        self.doubleSpinBox_singleRun_U.setObjectName(_fromUtf8("doubleSpinBox_singleRun_U"))
        self.gridLayout_4.addWidget(self.doubleSpinBox_singleRun_U, 0, 1, 1, 1)
        self.label_6 = QtGui.QLabel(self.gridLayoutWidget_4)
        self.label_6.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.gridLayout_4.addWidget(self.label_6, 1, 0, 1, 1)
        self.doubleSpinBox_singleRun_tsr = QtGui.QDoubleSpinBox(self.gridLayoutWidget_4)
        self.doubleSpinBox_singleRun_tsr.setMaximum(5.0)
        self.doubleSpinBox_singleRun_tsr.setSingleStep(0.1)
        self.doubleSpinBox_singleRun_tsr.setProperty("value", 2.0)
        self.doubleSpinBox_singleRun_tsr.setObjectName(_fromUtf8("doubleSpinBox_singleRun_tsr"))
        self.gridLayout_4.addWidget(self.doubleSpinBox_singleRun_tsr, 1, 1, 1, 1)
        self.label_10 = QtGui.QLabel(self.gridLayoutWidget_4)
        self.label_10.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.gridLayout_4.addWidget(self.label_10, 2, 0, 1, 1)
        self.label_33 = QtGui.QLabel(self.gridLayoutWidget_4)
        self.label_33.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_33.setObjectName(_fromUtf8("label_33"))
        self.gridLayout_4.addWidget(self.label_33, 3, 0, 1, 1)
        self.doubleSpinBox_singleRun_z_H = QtGui.QDoubleSpinBox(self.gridLayoutWidget_4)
        self.doubleSpinBox_singleRun_z_H.setProperty("value", 0.25)
        self.doubleSpinBox_singleRun_z_H.setObjectName(_fromUtf8("doubleSpinBox_singleRun_z_H"))
        self.gridLayout_4.addWidget(self.doubleSpinBox_singleRun_z_H, 3, 1, 1, 1)
        self.toolButtonOpenShakedown = QtGui.QToolButton(self.gridLayoutWidget_4)
        self.toolButtonOpenShakedown.setObjectName(_fromUtf8("toolButtonOpenShakedown"))
        self.gridLayout_4.addWidget(self.toolButtonOpenShakedown, 0, 2, 1, 1)
        self.tabWidgetMode.addTab(self.tabSingleRun, _fromUtf8(""))
        self.tabTestPlan = QtGui.QWidget()
        self.tabTestPlan.setObjectName(_fromUtf8("tabTestPlan"))
        self.tableWidgetTestPlan = QtGui.QTableWidget(self.tabTestPlan)
        self.tableWidgetTestPlan.setGeometry(QtCore.QRect(10, 40, 361, 301))
        self.tableWidgetTestPlan.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.tableWidgetTestPlan.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.tableWidgetTestPlan.setEditTriggers(QtGui.QAbstractItemView.NoEditTriggers)
        self.tableWidgetTestPlan.setSelectionMode(QtGui.QAbstractItemView.NoSelection)
        self.tableWidgetTestPlan.setTextElideMode(QtCore.Qt.ElideMiddle)
        self.tableWidgetTestPlan.setObjectName(_fromUtf8("tableWidgetTestPlan"))
        self.tableWidgetTestPlan.setColumnCount(6)
        self.tableWidgetTestPlan.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.tableWidgetTestPlan.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidgetTestPlan.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidgetTestPlan.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidgetTestPlan.setHorizontalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidgetTestPlan.setHorizontalHeaderItem(4, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidgetTestPlan.setHorizontalHeaderItem(5, item)
        self.tableWidgetTestPlan.horizontalHeader().setDefaultSectionSize(57)
        self.tableWidgetTestPlan.horizontalHeader().setMinimumSectionSize(20)
        self.tableWidgetTestPlan.verticalHeader().setVisible(False)
        self.tableWidgetTestPlan.verticalHeader().setDefaultSectionSize(15)
        self.tableWidgetTestPlan.verticalHeader().setHighlightSections(False)
        self.tableWidgetTestPlan.verticalHeader().setMinimumSectionSize(15)
        self.comboBox_testPlanSection = QtGui.QComboBox(self.tabTestPlan)
        self.comboBox_testPlanSection.setGeometry(QtCore.QRect(60, 10, 131, 22))
        self.comboBox_testPlanSection.setObjectName(_fromUtf8("comboBox_testPlanSection"))
        self.label_32 = QtGui.QLabel(self.tabTestPlan)
        self.label_32.setGeometry(QtCore.QRect(10, 10, 41, 21))
        self.label_32.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_32.setObjectName(_fromUtf8("label_32"))
        self.toolButtonOpenSection = QtGui.QToolButton(self.tabTestPlan)
        self.toolButtonOpenSection.setGeometry(QtCore.QRect(200, 11, 25, 20))
        self.toolButtonOpenSection.setObjectName(_fromUtf8("toolButtonOpenSection"))
        self.tabWidgetMode.addTab(self.tabTestPlan, _fromUtf8(""))
        self.tabProcessing = QtGui.QWidget()
        self.tabProcessing.setObjectName(_fromUtf8("tabProcessing"))
        self.groupBox = QtGui.QGroupBox(self.tabProcessing)
        self.groupBox.setGeometry(QtCore.QRect(10, 180, 181, 111))
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.gridLayoutWidget_5 = QtGui.QWidget(self.groupBox)
        self.gridLayoutWidget_5.setGeometry(QtCore.QRect(10, 20, 160, 80))
        self.gridLayoutWidget_5.setObjectName(_fromUtf8("gridLayoutWidget_5"))
        self.gridLayout_5 = QtGui.QGridLayout(self.gridLayoutWidget_5)
        self.gridLayout_5.setMargin(0)
        self.gridLayout_5.setObjectName(_fromUtf8("gridLayout_5"))
        self.label_20 = QtGui.QLabel(self.gridLayoutWidget_5)
        self.label_20.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_20.setObjectName(_fromUtf8("label_20"))
        self.gridLayout_5.addWidget(self.label_20, 1, 0, 1, 1)
        self.label_24 = QtGui.QLabel(self.gridLayoutWidget_5)
        self.label_24.setObjectName(_fromUtf8("label_24"))
        self.gridLayout_5.addWidget(self.label_24, 1, 1, 1, 1)
        self.label_25 = QtGui.QLabel(self.gridLayoutWidget_5)
        self.label_25.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_25.setObjectName(_fromUtf8("label_25"))
        self.gridLayout_5.addWidget(self.label_25, 2, 0, 1, 1)
        self.label_29 = QtGui.QLabel(self.gridLayoutWidget_5)
        self.label_29.setObjectName(_fromUtf8("label_29"))
        self.gridLayout_5.addWidget(self.label_29, 2, 1, 1, 1)
        self.label_30 = QtGui.QLabel(self.gridLayoutWidget_5)
        self.label_30.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_30.setObjectName(_fromUtf8("label_30"))
        self.gridLayout_5.addWidget(self.label_30, 0, 0, 1, 1)
        self.label_31 = QtGui.QLabel(self.gridLayoutWidget_5)
        self.label_31.setObjectName(_fromUtf8("label_31"))
        self.gridLayout_5.addWidget(self.label_31, 0, 1, 1, 1)
        self.groupBox_2 = QtGui.QGroupBox(self.tabProcessing)
        self.groupBox_2.setGeometry(QtCore.QRect(10, 10, 181, 141))
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.gridLayoutWidget_2 = QtGui.QWidget(self.groupBox_2)
        self.gridLayoutWidget_2.setGeometry(QtCore.QRect(10, 20, 161, 111))
        self.gridLayoutWidget_2.setObjectName(_fromUtf8("gridLayoutWidget_2"))
        self.gridLayout_2 = QtGui.QGridLayout(self.gridLayoutWidget_2)
        self.gridLayout_2.setMargin(0)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.label_23 = QtGui.QLabel(self.gridLayoutWidget_2)
        self.label_23.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_23.setObjectName(_fromUtf8("label_23"))
        self.gridLayout_2.addWidget(self.label_23, 1, 0, 1, 1)
        self.comboBox = QtGui.QComboBox(self.gridLayoutWidget_2)
        self.comboBox.setObjectName(_fromUtf8("comboBox"))
        self.gridLayout_2.addWidget(self.comboBox, 1, 1, 1, 1)
        self.label_21 = QtGui.QLabel(self.gridLayoutWidget_2)
        self.label_21.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_21.setObjectName(_fromUtf8("label_21"))
        self.gridLayout_2.addWidget(self.label_21, 2, 0, 1, 1)
        self.label_22 = QtGui.QLabel(self.gridLayoutWidget_2)
        self.label_22.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_22.setObjectName(_fromUtf8("label_22"))
        self.gridLayout_2.addWidget(self.label_22, 3, 0, 1, 1)
        self.doubleSpinBox_t1 = QtGui.QDoubleSpinBox(self.gridLayoutWidget_2)
        self.doubleSpinBox_t1.setObjectName(_fromUtf8("doubleSpinBox_t1"))
        self.gridLayout_2.addWidget(self.doubleSpinBox_t1, 2, 1, 1, 1)
        self.doubleSpinBox_t2 = QtGui.QDoubleSpinBox(self.gridLayoutWidget_2)
        self.doubleSpinBox_t2.setObjectName(_fromUtf8("doubleSpinBox_t2"))
        self.gridLayout_2.addWidget(self.doubleSpinBox_t2, 3, 1, 1, 1)
        self.label_28 = QtGui.QLabel(self.gridLayoutWidget_2)
        self.label_28.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_28.setObjectName(_fromUtf8("label_28"))
        self.gridLayout_2.addWidget(self.label_28, 0, 0, 1, 1)
        self.comboBoxProcessSection = QtGui.QComboBox(self.gridLayoutWidget_2)
        self.comboBoxProcessSection.setObjectName(_fromUtf8("comboBoxProcessSection"))
        self.gridLayout_2.addWidget(self.comboBoxProcessSection, 0, 1, 1, 1)
        self.commandLinkButton = QtGui.QCommandLinkButton(self.tabProcessing)
        self.commandLinkButton.setGeometry(QtCore.QRect(260, 260, 101, 41))
        self.commandLinkButton.setObjectName(_fromUtf8("commandLinkButton"))
        self.checkBox = QtGui.QCheckBox(self.tabProcessing)
        self.checkBox.setGeometry(QtCore.QRect(270, 240, 76, 17))
        self.checkBox.setObjectName(_fromUtf8("checkBox"))
        self.tabWidgetMode.addTab(self.tabProcessing, _fromUtf8(""))
        self.dockWidgetNISignals = QtGui.QDockWidget(self.centralwidget)
        self.dockWidgetNISignals.setGeometry(QtCore.QRect(400, 0, 360, 891))
        self.dockWidgetNISignals.setMinimumSize(QtCore.QSize(360, 38))
        self.dockWidgetNISignals.setFloating(False)
        self.dockWidgetNISignals.setAllowedAreas(QtCore.Qt.AllDockWidgetAreas)
        self.dockWidgetNISignals.setObjectName(_fromUtf8("dockWidgetNISignals"))
        self.dockWidgetContents_2 = QtGui.QWidget()
        self.dockWidgetContents_2.setObjectName(_fromUtf8("dockWidgetContents_2"))
        self.verticalLayoutWidget_2 = QtGui.QWidget(self.dockWidgetContents_2)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(10, 5, 341, 851))
        self.verticalLayoutWidget_2.setObjectName(_fromUtf8("verticalLayoutWidget_2"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_2.setMargin(0)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.label = QtGui.QLabel(self.verticalLayoutWidget_2)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName(_fromUtf8("label"))
        self.verticalLayout_2.addWidget(self.label)
        self.plotTorque = CurveWidget(self.verticalLayoutWidget_2)
        self.plotTorque.setOrientation(QtCore.Qt.Horizontal)
        self.plotTorque.setObjectName(_fromUtf8("plotTorque"))
        self.verticalLayout_2.addWidget(self.plotTorque)
        self.label_2 = QtGui.QLabel(self.verticalLayoutWidget_2)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.verticalLayout_2.addWidget(self.label_2)
        self.plotDrag = CurveWidget(self.verticalLayoutWidget_2)
        self.plotDrag.setOrientation(QtCore.Qt.Horizontal)
        self.plotDrag.setObjectName(_fromUtf8("plotDrag"))
        self.verticalLayout_2.addWidget(self.plotDrag)
        self.label_12 = QtGui.QLabel(self.verticalLayoutWidget_2)
        self.label_12.setAlignment(QtCore.Qt.AlignCenter)
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.verticalLayout_2.addWidget(self.label_12)
        self.plotDragL = CurveWidget(self.verticalLayoutWidget_2)
        self.plotDragL.setOrientation(QtCore.Qt.Horizontal)
        self.plotDragL.setObjectName(_fromUtf8("plotDragL"))
        self.verticalLayout_2.addWidget(self.plotDragL)
        self.label_13 = QtGui.QLabel(self.verticalLayoutWidget_2)
        self.label_13.setAlignment(QtCore.Qt.AlignCenter)
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.verticalLayout_2.addWidget(self.label_13)
        self.plotDragR = CurveWidget(self.verticalLayoutWidget_2)
        self.plotDragR.setOrientation(QtCore.Qt.Horizontal)
        self.plotDragR.setObjectName(_fromUtf8("plotDragR"))
        self.verticalLayout_2.addWidget(self.plotDragR)
        self.label_16 = QtGui.QLabel(self.verticalLayoutWidget_2)
        self.label_16.setAlignment(QtCore.Qt.AlignCenter)
        self.label_16.setObjectName(_fromUtf8("label_16"))
        self.verticalLayout_2.addWidget(self.label_16)
        self.plotRPM_ni = CurveWidget(self.verticalLayoutWidget_2)
        self.plotRPM_ni.setOrientation(QtCore.Qt.Horizontal)
        self.plotRPM_ni.setObjectName(_fromUtf8("plotRPM_ni"))
        self.verticalLayout_2.addWidget(self.plotRPM_ni)
        self.dockWidgetNISignals.setWidget(self.dockWidgetContents_2)
        self.dockWidget_acscontrol = QtGui.QDockWidget(self.centralwidget)
        self.dockWidget_acscontrol.setGeometry(QtCore.QRect(10, 390, 381, 501))
        self.dockWidget_acscontrol.setFloating(False)
        self.dockWidget_acscontrol.setObjectName(_fromUtf8("dockWidget_acscontrol"))
        self.dockWidgetContents_3 = QtGui.QWidget()
        self.dockWidgetContents_3.setObjectName(_fromUtf8("dockWidgetContents_3"))
        self.verticalLayoutWidget = QtGui.QWidget(self.dockWidgetContents_3)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(0, 120, 371, 351))
        self.verticalLayoutWidget.setObjectName(_fromUtf8("verticalLayoutWidget"))
        self.verticalLayout = QtGui.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setMargin(0)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.label_26 = QtGui.QLabel(self.verticalLayoutWidget)
        self.label_26.setAlignment(QtCore.Qt.AlignCenter)
        self.label_26.setObjectName(_fromUtf8("label_26"))
        self.verticalLayout.addWidget(self.label_26)
        self.plotTowSpeed = CurveWidget(self.verticalLayoutWidget)
        self.plotTowSpeed.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.plotTowSpeed.setOrientation(QtCore.Qt.Horizontal)
        self.plotTowSpeed.setObjectName(_fromUtf8("plotTowSpeed"))
        self.verticalLayout.addWidget(self.plotTowSpeed)
        self.label_27 = QtGui.QLabel(self.verticalLayoutWidget)
        self.label_27.setAlignment(QtCore.Qt.AlignCenter)
        self.label_27.setObjectName(_fromUtf8("label_27"))
        self.verticalLayout.addWidget(self.label_27)
        self.plotRPM_acs = CurveWidget(self.verticalLayoutWidget)
        self.plotRPM_acs.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.plotRPM_acs.setOrientation(QtCore.Qt.Horizontal)
        self.plotRPM_acs.setObjectName(_fromUtf8("plotRPM_acs"))
        self.verticalLayout.addWidget(self.plotRPM_acs)
        self.tableWidget_acs = QtGui.QTableWidget(self.dockWidgetContents_3)
        self.tableWidget_acs.setGeometry(QtCore.QRect(0, 0, 381, 112))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tableWidget_acs.sizePolicy().hasHeightForWidth())
        self.tableWidget_acs.setSizePolicy(sizePolicy)
        self.tableWidget_acs.setMinimumSize(QtCore.QSize(0, 112))
        self.tableWidget_acs.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.tableWidget_acs.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.tableWidget_acs.setEditTriggers(QtGui.QAbstractItemView.NoEditTriggers)
        self.tableWidget_acs.setProperty("showDropIndicator", True)
        self.tableWidget_acs.setDragDropOverwriteMode(False)
        self.tableWidget_acs.setSelectionMode(QtGui.QAbstractItemView.NoSelection)
        self.tableWidget_acs.setShowGrid(True)
        self.tableWidget_acs.setObjectName(_fromUtf8("tableWidget_acs"))
        self.tableWidget_acs.setColumnCount(6)
        self.tableWidget_acs.setRowCount(4)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_acs.setVerticalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_acs.setVerticalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_acs.setVerticalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_acs.setVerticalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_acs.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_acs.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_acs.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_acs.setHorizontalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_acs.setHorizontalHeaderItem(4, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_acs.setHorizontalHeaderItem(5, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_acs.setItem(0, 0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_acs.setItem(1, 0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_acs.setItem(2, 0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_acs.setItem(3, 0, item)
        self.tableWidget_acs.horizontalHeader().setDefaultSectionSize(64)
        self.tableWidget_acs.horizontalHeader().setMinimumSectionSize(23)
        self.tableWidget_acs.horizontalHeader().setStretchLastSection(True)
        self.tableWidget_acs.verticalHeader().setVisible(False)
        self.tableWidget_acs.verticalHeader().setCascadingSectionResizes(False)
        self.tableWidget_acs.verticalHeader().setDefaultSectionSize(22)
        self.tableWidget_acs.verticalHeader().setHighlightSections(False)
        self.tableWidget_acs.verticalHeader().setMinimumSectionSize(15)
        self.tableWidget_acs.verticalHeader().setSortIndicatorShown(False)
        self.tableWidget_acs.verticalHeader().setStretchLastSection(False)
        self.dockWidget_acscontrol.setWidget(self.dockWidgetContents_3)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1126, 21))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuFile = QtGui.QMenu(self.menubar)
        self.menuFile.setObjectName(_fromUtf8("menuFile"))
        self.menuHoming = QtGui.QMenu(self.menubar)
        self.menuHoming.setObjectName(_fromUtf8("menuHoming"))
        self.menuView = QtGui.QMenu(self.menubar)
        self.menuView.setObjectName(_fromUtf8("menuView"))
        self.menuSetings = QtGui.QMenu(self.menubar)
        self.menuSetings.setObjectName(_fromUtf8("menuSetings"))
        self.menuTest_Plan = QtGui.QMenu(self.menubar)
        self.menuTest_Plan.setObjectName(_fromUtf8("menuTest_Plan"))
        self.menuHelp = QtGui.QMenu(self.menubar)
        self.menuHelp.setObjectName(_fromUtf8("menuHelp"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)
        self.toolBar = QtGui.QToolBar(MainWindow)
        self.toolBar.setToolTip(_fromUtf8(""))
        self.toolBar.setObjectName(_fromUtf8("toolBar"))
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.dockWidgetVectrino = QtGui.QDockWidget(MainWindow)
        self.dockWidgetVectrino.setMinimumSize(QtCore.QSize(360, 38))
        self.dockWidgetVectrino.setObjectName(_fromUtf8("dockWidgetVectrino"))
        self.dockWidgetContents = QtGui.QWidget()
        self.dockWidgetContents.setObjectName(_fromUtf8("dockWidgetContents"))
        self.verticalLayoutWidget_3 = QtGui.QWidget(self.dockWidgetContents)
        self.verticalLayoutWidget_3.setGeometry(QtCore.QRect(10, 1, 341, 861))
        self.verticalLayoutWidget_3.setObjectName(_fromUtf8("verticalLayoutWidget_3"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.verticalLayoutWidget_3)
        self.verticalLayout_3.setMargin(0)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.label_vecu = QtGui.QLabel(self.verticalLayoutWidget_3)
        self.label_vecu.setAlignment(QtCore.Qt.AlignCenter)
        self.label_vecu.setObjectName(_fromUtf8("label_vecu"))
        self.verticalLayout_3.addWidget(self.label_vecu)
        self.plotVecU = CurveWidget(self.verticalLayoutWidget_3)
        self.plotVecU.setOrientation(QtCore.Qt.Horizontal)
        self.plotVecU.setObjectName(_fromUtf8("plotVecU"))
        self.verticalLayout_3.addWidget(self.plotVecU)
        self.label_11 = QtGui.QLabel(self.verticalLayoutWidget_3)
        self.label_11.setAlignment(QtCore.Qt.AlignCenter)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.verticalLayout_3.addWidget(self.label_11)
        self.plotVecV = CurveWidget(self.verticalLayoutWidget_3)
        self.plotVecV.setOrientation(QtCore.Qt.Horizontal)
        self.plotVecV.setObjectName(_fromUtf8("plotVecV"))
        self.verticalLayout_3.addWidget(self.plotVecV)
        self.label_14 = QtGui.QLabel(self.verticalLayoutWidget_3)
        self.label_14.setAlignment(QtCore.Qt.AlignCenter)
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.verticalLayout_3.addWidget(self.label_14)
        self.plotVecW = CurveWidget(self.verticalLayoutWidget_3)
        self.plotVecW.setOrientation(QtCore.Qt.Horizontal)
        self.plotVecW.setObjectName(_fromUtf8("plotVecW"))
        self.verticalLayout_3.addWidget(self.plotVecW)
        self.label_15 = QtGui.QLabel(self.verticalLayoutWidget_3)
        self.label_15.setAlignment(QtCore.Qt.AlignCenter)
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.verticalLayout_3.addWidget(self.label_15)
        self.plotVecCorr = CurveWidget(self.verticalLayoutWidget_3)
        self.plotVecCorr.setOrientation(QtCore.Qt.Horizontal)
        self.plotVecCorr.setObjectName(_fromUtf8("plotVecCorr"))
        self.verticalLayout_3.addWidget(self.plotVecCorr)
        self.label_5 = QtGui.QLabel(self.verticalLayoutWidget_3)
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.verticalLayout_3.addWidget(self.label_5)
        self.plotVecSNR = CurveWidget(self.verticalLayoutWidget_3)
        self.plotVecSNR.setOrientation(QtCore.Qt.Horizontal)
        self.plotVecSNR.setObjectName(_fromUtf8("plotVecSNR"))
        self.verticalLayout_3.addWidget(self.plotVecSNR)
        self.dockWidgetVectrino.setWidget(self.dockWidgetContents)
        MainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(2), self.dockWidgetVectrino)
        self.toolBar_DAQ = QtGui.QToolBar(MainWindow)
        self.toolBar_DAQ.setObjectName(_fromUtf8("toolBar_DAQ"))
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar_DAQ)
        self.toolBar_directory = QtGui.QToolBar(MainWindow)
        self.toolBar_directory.setObjectName(_fromUtf8("toolBar_directory"))
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar_directory)
        self.actionStart = QtGui.QAction(MainWindow)
        self.actionStart.setCheckable(True)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/play.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionStart.setIcon(icon1)
        self.actionStart.setObjectName(_fromUtf8("actionStart"))
        self.actionQuit = QtGui.QAction(MainWindow)
        self.actionQuit.setObjectName(_fromUtf8("actionQuit"))
        self.actionCOM_Port = QtGui.QAction(MainWindow)
        self.actionCOM_Port.setObjectName(_fromUtf8("actionCOM_Port"))
        self.actionHome_Tow = QtGui.QAction(MainWindow)
        self.actionHome_Tow.setObjectName(_fromUtf8("actionHome_Tow"))
        self.actionEnable_Tow = QtGui.QAction(MainWindow)
        self.actionEnable_Tow.setCheckable(True)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/tow_icon_b.ico")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionEnable_Tow.setIcon(icon2)
        self.actionEnable_Tow.setObjectName(_fromUtf8("actionEnable_Tow"))
        self.actionHome_Turbine = QtGui.QAction(MainWindow)
        self.actionHome_Turbine.setObjectName(_fromUtf8("actionHome_Turbine"))
        self.actionHome_y = QtGui.QAction(MainWindow)
        self.actionHome_y.setObjectName(_fromUtf8("actionHome_y"))
        self.actionHome_z = QtGui.QAction(MainWindow)
        self.actionHome_z.setObjectName(_fromUtf8("actionHome_z"))
        self.actionEdit_Configuration = QtGui.QAction(MainWindow)
        self.actionEdit_Configuration.setObjectName(_fromUtf8("actionEdit_Configuration"))
        self.actionMonitor_NI = QtGui.QAction(MainWindow)
        self.actionMonitor_NI.setCheckable(True)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/max.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionMonitor_NI.setIcon(icon3)
        self.actionMonitor_NI.setObjectName(_fromUtf8("actionMonitor_NI"))
        self.actionMonitor_Vectrino = QtGui.QAction(MainWindow)
        self.actionMonitor_Vectrino.setCheckable(True)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/vectrino.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionMonitor_Vectrino.setIcon(icon4)
        self.actionMonitor_Vectrino.setObjectName(_fromUtf8("actionMonitor_Vectrino"))
        self.actionVectrino = QtGui.QAction(MainWindow)
        self.actionVectrino.setObjectName(_fromUtf8("actionVectrino"))
        self.actionTurbine_Characteristics = QtGui.QAction(MainWindow)
        self.actionTurbine_Characteristics.setObjectName(_fromUtf8("actionTurbine_Characteristics"))
        self.actionImportTestPlan = QtGui.QAction(MainWindow)
        self.actionImportTestPlan.setObjectName(_fromUtf8("actionImportTestPlan"))
        self.actionAbort = QtGui.QAction(MainWindow)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/agt_stop.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionAbort.setIcon(icon5)
        self.actionAbort.setObjectName(_fromUtf8("actionAbort"))
        self.actionEnable_Turbine = QtGui.QAction(MainWindow)
        self.actionEnable_Turbine.setCheckable(True)
        self.actionEnable_Turbine.setIcon(icon)
        self.actionEnable_Turbine.setObjectName(_fromUtf8("actionEnable_Turbine"))
        self.actionEnable_y = QtGui.QAction(MainWindow)
        self.actionEnable_y.setCheckable(True)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/agt_back.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionEnable_y.setIcon(icon6)
        self.actionEnable_y.setObjectName(_fromUtf8("actionEnable_y"))
        self.actionEnable_z = QtGui.QAction(MainWindow)
        self.actionEnable_z.setCheckable(True)
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/up.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionEnable_z.setIcon(icon7)
        self.actionEnable_z.setObjectName(_fromUtf8("actionEnable_z"))
        self.actionEnable_All = QtGui.QAction(MainWindow)
        self.actionEnable_All.setCheckable(True)
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/button_ok.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionEnable_All.setIcon(icon8)
        self.actionEnable_All.setObjectName(_fromUtf8("actionEnable_All"))
        self.actionMonitor_ACS = QtGui.QAction(MainWindow)
        self.actionMonitor_ACS.setCheckable(True)
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/acs.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionMonitor_ACS.setIcon(icon9)
        self.actionMonitor_ACS.setObjectName(_fromUtf8("actionMonitor_ACS"))
        self.actionAbout = QtGui.QAction(MainWindow)
        self.actionAbout.setObjectName(_fromUtf8("actionAbout"))
        self.menuFile.addAction(self.actionQuit)
        self.menuHoming.addAction(self.actionHome_Tow)
        self.menuHoming.addAction(self.actionHome_Turbine)
        self.menuHoming.addAction(self.actionHome_y)
        self.menuHoming.addAction(self.actionHome_z)
        self.menuSetings.addAction(self.actionVectrino)
        self.menuSetings.addAction(self.actionTurbine_Characteristics)
        self.menuTest_Plan.addAction(self.actionImportTestPlan)
        self.menuHelp.addAction(self.actionAbout)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuView.menuAction())
        self.menubar.addAction(self.menuSetings.menuAction())
        self.menubar.addAction(self.menuHoming.menuAction())
        self.menubar.addAction(self.menuTest_Plan.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())
        self.toolBar.addAction(self.actionStart)
        self.toolBar.addAction(self.actionAbort)
        self.toolBar_DAQ.addAction(self.actionMonitor_ACS)
        self.toolBar_DAQ.addAction(self.actionMonitor_NI)
        self.toolBar_DAQ.addAction(self.actionMonitor_Vectrino)

        self.retranslateUi(MainWindow)
        self.tabWidgetMode.setCurrentIndex(2)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "TurbineDAQ", None, QtGui.QApplication.UnicodeUTF8))
        self.label_19.setText(QtGui.QApplication.translate("MainWindow", "End U (m/s)", None, QtGui.QApplication.UnicodeUTF8))
        self.label_18.setText(QtGui.QApplication.translate("MainWindow", "Step (m/s)", None, QtGui.QApplication.UnicodeUTF8))
        self.label_17.setText(QtGui.QApplication.translate("MainWindow", "Start U (m/s)", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidgetMode.setTabText(self.tabWidgetMode.indexOf(self.tabTareDrag), QtGui.QApplication.translate("MainWindow", "Tare Drag", None, QtGui.QApplication.UnicodeUTF8))
        self.label_9.setText(QtGui.QApplication.translate("MainWindow", "U_ref (m/s)", None, QtGui.QApplication.UnicodeUTF8))
        self.label_8.setText(QtGui.QApplication.translate("MainWindow", "End TSR", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("MainWindow", "Start TSR", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("MainWindow", "Step", None, QtGui.QApplication.UnicodeUTF8))
        self.label_startTsrRpm.setText(QtGui.QApplication.translate("MainWindow", "= RPM", None, QtGui.QApplication.UnicodeUTF8))
        self.label_stopTsrRpm.setText(QtGui.QApplication.translate("MainWindow", "= RPM", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidgetMode.setTabText(self.tabWidgetMode.indexOf(self.tabTareTorque), QtGui.QApplication.translate("MainWindow", "Tare Torque", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("MainWindow", "Tow Speed (m/s)", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("MainWindow", "Tip Speed Ratio", None, QtGui.QApplication.UnicodeUTF8))
        self.label_10.setText(QtGui.QApplication.translate("MainWindow", "y/R", None, QtGui.QApplication.UnicodeUTF8))
        self.label_33.setText(QtGui.QApplication.translate("MainWindow", "z/H", None, QtGui.QApplication.UnicodeUTF8))
        self.toolButtonOpenShakedown.setText(QtGui.QApplication.translate("MainWindow", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidgetMode.setTabText(self.tabWidgetMode.indexOf(self.tabSingleRun), QtGui.QApplication.translate("MainWindow", "Single Run", None, QtGui.QApplication.UnicodeUTF8))
        item = self.tableWidgetTestPlan.horizontalHeaderItem(0)
        item.setText(QtGui.QApplication.translate("MainWindow", "Run", None, QtGui.QApplication.UnicodeUTF8))
        item = self.tableWidgetTestPlan.horizontalHeaderItem(1)
        item.setText(QtGui.QApplication.translate("MainWindow", "U (m/s)", None, QtGui.QApplication.UnicodeUTF8))
        item = self.tableWidgetTestPlan.horizontalHeaderItem(2)
        item.setText(QtGui.QApplication.translate("MainWindow", "λ", None, QtGui.QApplication.UnicodeUTF8))
        item = self.tableWidgetTestPlan.horizontalHeaderItem(3)
        item.setText(QtGui.QApplication.translate("MainWindow", "y/R", None, QtGui.QApplication.UnicodeUTF8))
        item = self.tableWidgetTestPlan.horizontalHeaderItem(4)
        item.setText(QtGui.QApplication.translate("MainWindow", "z/H", None, QtGui.QApplication.UnicodeUTF8))
        item = self.tableWidgetTestPlan.horizontalHeaderItem(5)
        item.setText(QtGui.QApplication.translate("MainWindow", "Done?", None, QtGui.QApplication.UnicodeUTF8))
        self.label_32.setText(QtGui.QApplication.translate("MainWindow", "Section", None, QtGui.QApplication.UnicodeUTF8))
        self.toolButtonOpenSection.setText(QtGui.QApplication.translate("MainWindow", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidgetMode.setTabText(self.tabWidgetMode.indexOf(self.tabTestPlan), QtGui.QApplication.translate("MainWindow", "Test Plan", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox.setTitle(QtGui.QApplication.translate("MainWindow", "Results", None, QtGui.QApplication.UnicodeUTF8))
        self.label_20.setText(QtGui.QApplication.translate("MainWindow", "C_P", None, QtGui.QApplication.UnicodeUTF8))
        self.label_24.setText(QtGui.QApplication.translate("MainWindow", "TextLabel", None, QtGui.QApplication.UnicodeUTF8))
        self.label_25.setText(QtGui.QApplication.translate("MainWindow", "C_D", None, QtGui.QApplication.UnicodeUTF8))
        self.label_29.setText(QtGui.QApplication.translate("MainWindow", "TextLabel", None, QtGui.QApplication.UnicodeUTF8))
        self.label_30.setText(QtGui.QApplication.translate("MainWindow", "TSR", None, QtGui.QApplication.UnicodeUTF8))
        self.label_31.setText(QtGui.QApplication.translate("MainWindow", "TextLabel", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_2.setTitle(QtGui.QApplication.translate("MainWindow", "Parameters", None, QtGui.QApplication.UnicodeUTF8))
        self.label_23.setText(QtGui.QApplication.translate("MainWindow", "Run", None, QtGui.QApplication.UnicodeUTF8))
        self.label_21.setText(QtGui.QApplication.translate("MainWindow", "Start Time (s)", None, QtGui.QApplication.UnicodeUTF8))
        self.label_22.setText(QtGui.QApplication.translate("MainWindow", "End Time (s)", None, QtGui.QApplication.UnicodeUTF8))
        self.label_28.setText(QtGui.QApplication.translate("MainWindow", "Section", None, QtGui.QApplication.UnicodeUTF8))
        self.commandLinkButton.setText(QtGui.QApplication.translate("MainWindow", "Process", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox.setText(QtGui.QApplication.translate("MainWindow", "Plot?", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidgetMode.setTabText(self.tabWidgetMode.indexOf(self.tabProcessing), QtGui.QApplication.translate("MainWindow", "Processing", None, QtGui.QApplication.UnicodeUTF8))
        self.dockWidgetNISignals.setWindowTitle(QtGui.QApplication.translate("MainWindow", "NI Signals", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("MainWindow", "            Torque (Nm)", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("MainWindow", "            Drag (N)", None, QtGui.QApplication.UnicodeUTF8))
        self.label_12.setText(QtGui.QApplication.translate("MainWindow", "             Drag Left (N)", None, QtGui.QApplication.UnicodeUTF8))
        self.label_13.setText(QtGui.QApplication.translate("MainWindow", "            Drag Right (N)", None, QtGui.QApplication.UnicodeUTF8))
        self.label_16.setText(QtGui.QApplication.translate("MainWindow", "           Turbine RPM", None, QtGui.QApplication.UnicodeUTF8))
        self.dockWidget_acscontrol.setWindowTitle(QtGui.QApplication.translate("MainWindow", "ACS Controller", None, QtGui.QApplication.UnicodeUTF8))
        self.label_26.setText(QtGui.QApplication.translate("MainWindow", "             Tow Speed (m/s)", None, QtGui.QApplication.UnicodeUTF8))
        self.label_27.setText(QtGui.QApplication.translate("MainWindow", "           Turbine RPM", None, QtGui.QApplication.UnicodeUTF8))
        item = self.tableWidget_acs.horizontalHeaderItem(0)
        item.setText(QtGui.QApplication.translate("MainWindow", "Axis", None, QtGui.QApplication.UnicodeUTF8))
        item = self.tableWidget_acs.horizontalHeaderItem(1)
        item.setText(QtGui.QApplication.translate("MainWindow", "Enabled?", None, QtGui.QApplication.UnicodeUTF8))
        item = self.tableWidget_acs.horizontalHeaderItem(2)
        item.setText(QtGui.QApplication.translate("MainWindow", "Home #", None, QtGui.QApplication.UnicodeUTF8))
        item = self.tableWidget_acs.horizontalHeaderItem(3)
        item.setText(QtGui.QApplication.translate("MainWindow", "RPOS", None, QtGui.QApplication.UnicodeUTF8))
        item = self.tableWidget_acs.horizontalHeaderItem(4)
        item.setText(QtGui.QApplication.translate("MainWindow", "FPOS", None, QtGui.QApplication.UnicodeUTF8))
        item = self.tableWidget_acs.horizontalHeaderItem(5)
        item.setText(QtGui.QApplication.translate("MainWindow", "FVEL", None, QtGui.QApplication.UnicodeUTF8))
        __sortingEnabled = self.tableWidget_acs.isSortingEnabled()
        self.tableWidget_acs.setSortingEnabled(False)
        item = self.tableWidget_acs.item(0, 0)
        item.setText(QtGui.QApplication.translate("MainWindow", "tow", None, QtGui.QApplication.UnicodeUTF8))
        item = self.tableWidget_acs.item(1, 0)
        item.setText(QtGui.QApplication.translate("MainWindow", "turbine", None, QtGui.QApplication.UnicodeUTF8))
        item = self.tableWidget_acs.item(2, 0)
        item.setText(QtGui.QApplication.translate("MainWindow", "y", None, QtGui.QApplication.UnicodeUTF8))
        item = self.tableWidget_acs.item(3, 0)
        item.setText(QtGui.QApplication.translate("MainWindow", "z", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget_acs.setSortingEnabled(__sortingEnabled)
        self.menuFile.setTitle(QtGui.QApplication.translate("MainWindow", "File", None, QtGui.QApplication.UnicodeUTF8))
        self.menuHoming.setTitle(QtGui.QApplication.translate("MainWindow", "Homing", None, QtGui.QApplication.UnicodeUTF8))
        self.menuView.setTitle(QtGui.QApplication.translate("MainWindow", "View", None, QtGui.QApplication.UnicodeUTF8))
        self.menuSetings.setTitle(QtGui.QApplication.translate("MainWindow", "Settings", None, QtGui.QApplication.UnicodeUTF8))
        self.menuTest_Plan.setTitle(QtGui.QApplication.translate("MainWindow", "Test Plan", None, QtGui.QApplication.UnicodeUTF8))
        self.menuHelp.setTitle(QtGui.QApplication.translate("MainWindow", "Help", None, QtGui.QApplication.UnicodeUTF8))
        self.toolBar.setWindowTitle(QtGui.QApplication.translate("MainWindow", "toolBar", None, QtGui.QApplication.UnicodeUTF8))
        self.dockWidgetVectrino.setWindowTitle(QtGui.QApplication.translate("MainWindow", "Vectrino", None, QtGui.QApplication.UnicodeUTF8))
        self.label_vecu.setText(QtGui.QApplication.translate("MainWindow", "            u (m/s)", None, QtGui.QApplication.UnicodeUTF8))
        self.label_11.setText(QtGui.QApplication.translate("MainWindow", "          v (m/s)", None, QtGui.QApplication.UnicodeUTF8))
        self.label_14.setText(QtGui.QApplication.translate("MainWindow", "          w (m/s)", None, QtGui.QApplication.UnicodeUTF8))
        self.label_15.setText(QtGui.QApplication.translate("MainWindow", "            Correlation (%)", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("MainWindow", "            SNR (dB)", None, QtGui.QApplication.UnicodeUTF8))
        self.toolBar_DAQ.setWindowTitle(QtGui.QApplication.translate("MainWindow", "toolBar_2", None, QtGui.QApplication.UnicodeUTF8))
        self.toolBar_directory.setWindowTitle(QtGui.QApplication.translate("MainWindow", "toolBar_2", None, QtGui.QApplication.UnicodeUTF8))
        self.actionStart.setText(QtGui.QApplication.translate("MainWindow", "Start", None, QtGui.QApplication.UnicodeUTF8))
        self.actionQuit.setText(QtGui.QApplication.translate("MainWindow", "Quit", None, QtGui.QApplication.UnicodeUTF8))
        self.actionCOM_Port.setText(QtGui.QApplication.translate("MainWindow", "COM Port", None, QtGui.QApplication.UnicodeUTF8))
        self.actionHome_Tow.setText(QtGui.QApplication.translate("MainWindow", "Home Tow Axis", None, QtGui.QApplication.UnicodeUTF8))
        self.actionEnable_Tow.setText(QtGui.QApplication.translate("MainWindow", "Enable Tow", None, QtGui.QApplication.UnicodeUTF8))
        self.actionEnable_Tow.setToolTip(QtGui.QApplication.translate("MainWindow", "Tow Axis Enable", None, QtGui.QApplication.UnicodeUTF8))
        self.actionHome_Turbine.setText(QtGui.QApplication.translate("MainWindow", "Home Turbine Axis", None, QtGui.QApplication.UnicodeUTF8))
        self.actionHome_y.setText(QtGui.QApplication.translate("MainWindow", "Home y-axis", None, QtGui.QApplication.UnicodeUTF8))
        self.actionHome_z.setText(QtGui.QApplication.translate("MainWindow", "Home z-axis", None, QtGui.QApplication.UnicodeUTF8))
        self.actionEdit_Configuration.setText(QtGui.QApplication.translate("MainWindow", "Edit Configuration...", None, QtGui.QApplication.UnicodeUTF8))
        self.actionMonitor_NI.setText(QtGui.QApplication.translate("MainWindow", "Monitor NI Signals", None, QtGui.QApplication.UnicodeUTF8))
        self.actionMonitor_NI.setToolTip(QtGui.QApplication.translate("MainWindow", "Monitor NI Signals", None, QtGui.QApplication.UnicodeUTF8))
        self.actionMonitor_Vectrino.setText(QtGui.QApplication.translate("MainWindow", "Monitor Vectrino", None, QtGui.QApplication.UnicodeUTF8))
        self.actionMonitor_Vectrino.setToolTip(QtGui.QApplication.translate("MainWindow", "Monitor Vectrino Signals", None, QtGui.QApplication.UnicodeUTF8))
        self.actionVectrino.setText(QtGui.QApplication.translate("MainWindow", "Vectrino...", None, QtGui.QApplication.UnicodeUTF8))
        self.actionTurbine_Characteristics.setText(QtGui.QApplication.translate("MainWindow", "Turbine Characteristics...", None, QtGui.QApplication.UnicodeUTF8))
        self.actionImportTestPlan.setText(QtGui.QApplication.translate("MainWindow", "Reload", None, QtGui.QApplication.UnicodeUTF8))
        self.actionAbort.setText(QtGui.QApplication.translate("MainWindow", "Abort", None, QtGui.QApplication.UnicodeUTF8))
        self.actionAbort.setToolTip(QtGui.QApplication.translate("MainWindow", "Stop immediately and abort run", None, QtGui.QApplication.UnicodeUTF8))
        self.actionEnable_Turbine.setText(QtGui.QApplication.translate("MainWindow", "Enable Turbine", None, QtGui.QApplication.UnicodeUTF8))
        self.actionEnable_y.setText(QtGui.QApplication.translate("MainWindow", "Enable y", None, QtGui.QApplication.UnicodeUTF8))
        self.actionEnable_z.setText(QtGui.QApplication.translate("MainWindow", "Enable z", None, QtGui.QApplication.UnicodeUTF8))
        self.actionEnable_All.setText(QtGui.QApplication.translate("MainWindow", "Enable All", None, QtGui.QApplication.UnicodeUTF8))
        self.actionEnable_All.setToolTip(QtGui.QApplication.translate("MainWindow", "Enable all axes", None, QtGui.QApplication.UnicodeUTF8))
        self.actionMonitor_ACS.setText(QtGui.QApplication.translate("MainWindow", "Monitor ACS", None, QtGui.QApplication.UnicodeUTF8))
        self.actionMonitor_ACS.setToolTip(QtGui.QApplication.translate("MainWindow", "Monitor values in ACS controller", None, QtGui.QApplication.UnicodeUTF8))
        self.actionAbout.setText(QtGui.QApplication.translate("MainWindow", "About", None, QtGui.QApplication.UnicodeUTF8))

from guiqwt.plot import CurveWidget
import resources_rc
