[project]
name = "turbinedaq"
dynamic = ["version"]
readme = "README.md"
license = {file = "LICENSE"}

[build-system]
requires = ["setuptools >= 61.0"]
build-backend = "setuptools.build_meta"

[project.scripts]
turbinedaq = "turbinedaq.main:main"

[tool.setuptools]
packages = ["turbinedaq"]
