"""Functions to build ACS motion control programs."""

from __future__ import division, print_function

import os


AFT_TEMPLATE = """
! AUTO-GENERATED -- CHANGES WILL BE OVERWRITTEN
! Here we will try to continuously collect data from the INF4
global int collect_data
global real start_time
local int sample_period_ms
sample_period_ms = 1
global real ch1_force, ch2_force, ch3_force, ch4_force, ch1_force_mV, ch2_force_mV, ch3_force_mV, ch4_force_mV, aft_motor_torque, aft_motor_vel, s700_pos, s700_torque
global real aft_data(8)(100)
global real aft_data2(7)(100) ! 6/26/26 - New data array to collect load cell data in mV and AFT motor torque/speed
global real s700_data(3)(100) ! 6/26/26 - New data array to collect S700 F_POS (to resolve feedback velocity) and F_TORQUE (monitoring purposes)

! Read torque and target motor speed process data from AFT motor 
aft_motor_torque = COEREAD/2 (3, 0x6077, 0)
aft_motor_vel = COEREAD/4 (3, 0x60FF, 0) 

s700_pos = F_POS(5) * EFAC(5)
s700_torque = F_TORQUE(5) * 0.001 * 38

BLOCK
    ! Define start time from now
    start_time = TIME
    collect_data = 1
    DC/c aft_data, 100, sample_period_ms, TIME, ch1_force, ch2_force, ch3_force, ch4_force, FPOS(6), FVEL(6), FVEL(5)
    DC/c aft_data2, 100, sample_period_ms, TIME, ch1_force_mV, ch2_force_mV, ch3_force_mV, ch4_force_mV, aft_motor_torque, aft_motor_vel
    DC/c s700_data, 100, sample_period_ms, TIME, s700_pos, s700_torque ! F_POS in units of meters, F_TORQUE in units of Nm
END

! Continuously compute processed force values from the INF4
WHILE collect_data
    WAIT 1
END

STOPDC
STOP
"""

AFT_TOW_TEMPLATE = """
! This is a turbine tow program auto-generated by TurbineDAQ
! AUTO-GENERATED -- CHANGES WILL BE OVERWRITTEN
local real target, tsr, U, rpm, tacc, endpos, tzero, R, revs, dist_to_0, remainder 
global real data(3)(100)
global real start_time
global int collect_data
local int sample_period_ms, local int sample_period_ms, revs_int
sample_period_ms = {sample_period_ms}
global real ch1_force, ch2_force, ch3_force, ch4_force, ch1_force_mV, ch2_force_mV, ch3_force_mV, ch4_force_mV, position_actual, aft_motor_torque, aft_motor_vel, s700_pos, s700_torque
global real aft_data(8)({n_buffer_rows})
global real aft_data2(7)({n_buffer_rows}) ! 6/26/26 - New data array to collect load cell data in mV and AFT motor torque/speed
global real s700_data(3)({n_buffer_rows}) ! 6/26/26 - New data array to collect S700 F_POS (to resolve feedback velocity) and F_TORQUE (monitoring purposes)

collect_data = 0

tsr = {tsr}
U = {tow_speed}
R = {turbine_radius}

rpm = tsr*U/R*60/6.28318530718

target = 24.5       ! Do not exceed 24.9 for traverse at x/D = 1
endpos = {endpos}        ! Where to move carriage at end of tow
tacc = 5            ! Time (in seconds) for turbine angular acceleration
tzero = 2.5         ! Time (in seconds) to wait before starting

! Read torque and target motor speed process data from AFT motor 
aft_motor_torque = COEREAD/2 (3, 0x6077, 0)
aft_motor_vel = COEREAD/4 (3, 0x60FF, 0) 

s700_pos = F_POS(5) * EFAC(5)
s700_torque = F_TORQUE(5) * 0.001 * 38

VEL(5) = 0.5
ptp/e 5, 0

ACC(5) = 1.0
DEC(5) = 0.5
VEL(5) = U
JERK(5)= ACC(5)*10

! Set modulo on turbine axis (only needed if using simulator)
! DISABLE 6
! SLPMAX(6) = 60
! SLPMIN(6) = 0
! MFLAGS(6).#MODULO = 1

ACC(6) = rpm/tacc
VEL(6) = rpm
DEC(6) = ACC(6)
JERK(6)= ACC(6)*10

! Move turbine to zero if necessary
! if RPOS(6) <> 60 & RPOS(6) <> 0
!   ptp/e 6, 0
! end

! Allow oscillations in shaft to damp out
wait 3000

! Start controller data acquisition and send trigger pulse in same cycle
BLOCK
    ! Define start time from now
    start_time = TIME
    collect_data = 1
    DC/c aft_data, {n_buffer_rows}, sample_period_ms, TIME, ch1_force, ch2_force, ch3_force, ch4_force, FPOS(6), FVEL(6), RVEL(5)
    DC/c aft_data2, {n_buffer_rows}, sample_period_ms, TIME, ch1_force_mV, ch2_force_mV, ch3_force_mV, ch4_force_mV, aft_motor_torque, aft_motor_vel
    DC/c s700_data, {n_buffer_rows}, sample_period_ms, TIME, s700_pos, s700_torque! F_POS in units of meters, F_TORQUE in units of Nm
    ! Send trigger pulse for data acquisition
    OUT1.16 = 1
END

wait tzero*1000
jog/v 6, rpm
wait tacc*1000
ptp/e 5, target
HALT(6)
ACC(5) = 0.3
VEL(5) = 0.5
VEL(6) = 10

revs_int = position_actual / 360000
revs = position_actual / 360000
if revs_int > revs 
    revs_int = revs_int - 1
end
remainder = revs - revs_int
dist_to_0 = 60 - (60 * remainder) ! 60 = 360 degrees, find relative distance to 0 

ptp/re 6, dist_to_0 ! Perform PTP(6) before carriage starts moving, move instrumented blade to 0 degree position
ptp/e 5, endpos
STOPDC
collect_data = 0
OUT1.16 = 0

STOP
"""


def turbine_tow_prg(
    tow_speed,
    tsr,
    turbine_radius,
    endpos=0.0,
    prgdir="./acsprgs",
    turbine_type="CFT",
):
    """This function builds an ACSPL+ program for turbine towing."""
    if turbine_type == "CFT":
        with open(os.path.join(prgdir, "turbine_tow.prg")) as f:
            prg = f.read().format(
                tow_speed=tow_speed,
                tsr=tsr,
                turbine_radius=turbine_radius,
                endpos=endpos,
            )
    elif turbine_type == "AFT":
        prg = AFT_TOW_TEMPLATE.format(
            sample_period_ms=1/600*1000,
            tow_speed=tow_speed,
            tsr=tsr,
            turbine_radius=turbine_radius,
            endpos=endpos,
            n_buffer_rows=100,
        )
    return prg


def tare_torque_prg(rpm, dur, prgdir="./acsprgs"):
    """Builds a tare torque ACSPL+ program"""
    with open(os.path.join(prgdir, "tare_torque.prg")) as f:
        prg = f.read().format(rpm=rpm, dur=dur)
    return prg


def tare_drag_prg(tow_speed, prgdir="./acsprgs"):
    with open(os.path.join(prgdir, "tare_drag.prg")) as f:
        prg = f.read().format(tow_speed=tow_speed)
    return prg


def make_aft_prg(sample_period_ms=1/600*1000, n_buffer_rows=100) -> str:
    """Create an AFT program to load into the controller."""
    return AFT_TEMPLATE.format(
        sample_period_ms=sample_period_ms,
        n_buffer_rows=n_buffer_rows,
    )
